(() => {
  'use strict';

  const ENGLISH = new Map([
    ['[已隐藏]', '[redacted]'],
    ['工作目录', 'Working directory'],
    ['OpenSSH 配置及 Include 总计超过 4 MiB，已拒绝导入', 'OpenSSH configuration and Includes exceed 4 MiB; import rejected'],
    ['OpenSSH 配置及其 Include 文件中没有可导入的具体 Host 别名', 'No importable concrete Host aliases in OpenSSH configuration or Includes'],
    ['单个 OpenSSH 配置文件超过 1 MiB，已拒绝导入', 'An OpenSSH configuration file exceeds 1 MiB; import rejected'],
    ['发现的配置中没有可导入的服务器 Host 别名', 'No importable server Host aliases in the discovered configuration'],
    ['服务器设置文件中没有可导入的服务器', 'No importable servers in the configuration file'],
    ['服务器设置文件必须是受支持的 servers.toml version 2 或 3', 'Server configuration must use supported servers.toml version 2 or 3'],
    ['服务器设置文件超过 1 MiB，已拒绝导入', 'Server configuration exceeds 1 MiB; import rejected'],
    ['无法识别配置格式；请选择 servers.toml v2/v3 或 OpenSSH ~/.ssh/config', 'Unrecognized configuration format; choose servers.toml v2/v3 or OpenSSH ~/.ssh/config'],
    ['SSH 公钥不是有效的 UTF-8 文本', 'SSH public key is not valid UTF-8 text'],
    ['SSH 公钥二进制结构无效', 'Invalid SSH public-key binary structure'],
    ['SSH 公钥内容不是有效的 Base64', 'SSH public-key content is not valid Base64'],
    ['SSH 公钥内容过短', 'SSH public-key content is too short'], ['SSH 公钥必须是单行文本', 'SSH public key must be a single line'],
    ['SSH 公钥文件超过安全长度限制', 'SSH public-key file exceeds the safe length limit'],
    ['SSH 公钥格式无效', 'Invalid SSH public-key format'], ['SSH 公钥类型不受支持或格式无效', 'Unsupported SSH public-key type or invalid format'],
    ['SSH 公钥类型与内容不一致', 'SSH public-key type does not match its content'],
    ['SSH 公钥超过安全长度限制', 'SSH public key exceeds the safe length limit'],
    ['SSH 私钥文件无效或大小异常', 'SSH private-key file is invalid or has an unexpected size'],
    ['SSH 私钥权限过宽；请先在终端执行 chmod 600 后再试', 'SSH private-key permissions are too broad; run chmod 600 in a terminal and retry'],
    ['VRAM Radar 专用密钥位置已有不完整文件；为避免覆盖，请改用现有密钥或先人工检查', 'Incomplete files exist at the dedicated key location; choose an existing key or review manually to avoid overwriting them'],
    ['Windows 无法收紧 SSH 私钥访问权限', 'Windows could not restrict SSH private-key permissions'],
    ['Windows 缺少私钥权限管理工具 icacls', 'Windows private-key permission tool icacls is missing'],
    ['ssh-keygen 无法生成本地 Ed25519 密钥', 'ssh-keygen could not generate a local Ed25519 key'],
    ['专用密钥位置已存在，未覆盖任何文件', 'The dedicated key path already exists; no files were overwritten'],
    ['无法从私钥读取公钥；如私钥带口令，请选择对应的 .pub 公钥文件并先加载 ssh-agent', 'Could not derive the public key; for a passphrase-protected key, select its .pub file and load ssh-agent first'],
    ['无法创建本机 SSH Key 保存目录', 'Could not create the local SSH key directory'],
    ['无法启动本机 ssh-keygen', 'Could not start local ssh-keygen'], ['无法设置 SSH 私钥权限', 'Could not set SSH private-key permissions'],
    ['无法识别当前 Windows 用户', 'Could not identify the current Windows user'],
    ['无法读取 SSH 公钥文件', 'Could not read the SSH public-key file'], ['无法读取 SSH 私钥', 'Could not read the SSH private key'],
    ['无法验证 GitHub 下载服务器的 HTTPS 证书', 'Could not verify the GitHub download server HTTPS certificate'],
    ['更新下载被重定向到非 GitHub 地址', 'Update download redirected to a non-GitHub address'],
    ['更新文件 SHA-256 或大小校验失败', 'Update SHA-256 or size verification failed'],
    ['更新文件元数据不完整', 'Update file metadata is incomplete'],
    ['更新文件大小与 Release 元数据不一致', 'Update file size does not match Release metadata'],
    ['本地 SSH Key 操作超时', 'Local SSH key operation timed out'],
    ['本机未找到 ssh-keygen', 'ssh-keygen not found on this computer'],
    ['本机未找到 ssh-keygen；请先安装或启用系统 OpenSSH 客户端', 'ssh-keygen not found; install or enable the system OpenSSH client'],
    ['选择的公钥与私钥不匹配', 'Selected public and private keys do not match'],
    ['SSH 端点信息不完整，命令已保留原始连接语义。', 'SSH endpoint details are incomplete; the original connection semantics were preserved.'],
    ['SSH 配置包含条件、动态规则或未匹配到该 Host；命令已保留原始别名，连接时仍由 OpenSSH 完整解析。', 'SSH configuration contains conditional/dynamic rules or no matching Host; the original alias is preserved for OpenSSH to resolve.'],
    ['用户名使用本机 OpenSSH 默认值，命令已保留原始连接语义。', 'The username uses local OpenSSH defaults; original connection semantics were preserved.'],
    ['。请在设置中检查服务器配置文件路径和内容。', '. Check the server configuration file path and content in Settings.'],
    ['保存的服务器密码', 'saved server password'], ['当前用户名', 'current username'],
    ['GPU 或调度信息读取成功', 'GPU or scheduler information loaded successfully'],
    ['CPU 负载', 'CPU load'], ['GPU 数据', 'GPU data'], ['GPU 进程数据', 'GPU process data'],
    ['SSH 连接', 'SSH connection'], ['Slurm 任务队列读取（squeue）', 'Slurm job queue (squeue)'],
    ['Slurm 环境检测', 'Slurm environment discovery'], ['Slurm 节点清单读取（sinfo）', 'Slurm node inventory (sinfo)'],
    ['关闭窗口时只能选择收起到通知区域或退出', 'Closing the window must either hide it in the notification area or exit'],
    ['发送到服务器的数据超过安全上限', 'Data sent to the server exceeds the safety limit'],
    ['找不到 Windows PowerShell，请先复制 SSH 命令', 'Windows PowerShell not found; copy the SSH command first'],
    ['按单卡可用显存、是否需要跨节点以及可用 GPU 数排序', 'Sorted by free VRAM per GPU, cross-node requirements, and available GPU count'],
    ['收藏的 GPU 已空闲', 'A favorited GPU is free'], ['收藏的服务器有空闲 GPU', 'A favorited server has free GPUs'],
    ['文件夹提示', 'Folder notice'], ['文件夹条目名称', 'Folder entry name'], ['服务器名称', 'Server name'],
    ['未知的命令窗口类型', 'Unknown terminal type'], ['本地密钥', 'Local key'], ['保存配置', 'Save configuration'], ['免密验证', 'Passwordless sign-in verification'],
    ['安全恢复', 'Safe recovery'], ['结果数量', 'Result count'], ['自动监控已暂停', 'Automatic monitoring paused'],
    ['该阶段返回了非零状态；原始远端输出未写入脱敏诊断', 'This stage returned a nonzero status; raw remote output was excluded from redacted diagnostics'],
    ['请在 Mac 上使用“一键打开终端”', 'Use “Open Terminal” on a Mac'], ['请在 Windows 电脑上使用“一键打开 PowerShell”', 'Use “Open PowerShell” on Windows'],
    ['资源读取', 'Resource collection'], ['远端基础环境检测', 'Remote environment discovery'], ['远端账号检测', 'Remote account discovery'], ['部署公钥', 'Install public key'],
    ['无法创建应用运行锁，请检查本地数据目录权限', 'Could not create the application lock; check local data-directory permissions'],
    ['无法启动后台服务器刷新线程', 'Could not start the background server refresh thread'],
    ['这个 Profile 已经有一个运行实例', 'An instance is already running for this Profile'],
    ['本次运行已通过 --no-auto-import 禁用本机服务器配置自动发现；如需导入，请手动输入明确的 SSH Config 或 servers.toml 路径', 'Local configuration discovery is disabled by --no-auto-import; enter an explicit SSH Config or servers.toml path to import'],
    ['本次运行已通过 --no-auto-import 禁用默认配置查找；请手动输入明确的 SSH Config 或 servers.toml 路径', 'Default configuration discovery is disabled by --no-auto-import; enter an explicit SSH Config or servers.toml path'],
    ['已尝试显式配置、环境变量、常见/Nix/Guix 路径、Modules 索引、账号默认 shell、command/type/which/whereis、Spack、系统包数据库、限时目录扫描和交互式 Bash', 'Tried explicit configuration, environment variables, common/Nix/Guix paths, Modules, the default shell, command/type/which/whereis, Spack, package databases, bounded directory scans, and interactive Bash'],
    ['。当前没有可显示的 GPU 快照。', '. No GPU snapshot is available.'],
    ['。旧快照仅供参考，不计入顶部实时汇总。', '. The old snapshot is for reference only and excluded from the live summary.'],
    ['GPU 快照', 'GPU snapshot'], ['GPU 快照字段', 'GPU snapshot fields'],
    ['文件夹条目上限', 'folder entry limit'], ['文件夹深度', 'folder depth'], ['进程采集上限', 'process collection limit'],
    ['展开目录', 'expanded directory'], ['文件夹条目', 'folder entries'], ['目录版本', 'directory revision'],
    ['文件夹字段', 'folder fields'], ['文件夹结构', 'folder structure'], ['修改时间', 'modification time'],
    ['当前用户标识', 'current user identifier'], ['文件夹状态', 'folder state'], ['目录来源', 'directory source'],
    ['目录版本状态', 'directory revision state'], ['进程元数据', 'process metadata'], ['进程可见性状态', 'process visibility state'],
    ['调度快照', 'scheduler snapshot'], ['任务可见范围', 'job visibility scope'], ['任务详情能力状态', 'job detail capability'],
    ['压缩节点列表', 'compressed node list'], ['压缩节点步长', 'compressed node stride'], ['环境探测模式', 'environment discovery mode'],
    ['节点分配能力状态', 'node allocation capability'], ['节点清单探测模式', 'node inventory mode'], ['节点分配数据', 'node allocation data'],
    ['服务器返回的数据超过安全上限，已中止本次刷新', 'Server response exceeds the safety limit; this refresh was stopped'],
    ['Slurm 节点列表超过安全解析上限', 'Slurm node list exceeds the safe parsing limit'],
    ['nvidia-smi 没有返回 GPU', 'nvidia-smi returned no GPUs'], ['nvidia-smi 返回了无法识别的数值', 'nvidia-smi returned an unrecognized numeric value'],
    ['nvidia-smi 返回了无法识别的数据', 'nvidia-smi returned unrecognized data'], ['sinfo 返回了无法识别的数据', 'sinfo returned unrecognized data'],
    ['squeue 返回了无效的任务节点数', 'squeue returned an invalid job node count'], ['squeue 返回了无法识别的任务详情', 'squeue returned unrecognized job details'],
    ['本机 SSH ProxyCommand 缺少所需命令，请检查跳板或代理配置', 'SSH ProxyCommand requires a missing local command; check jump-host or proxy configuration'],
    ['本机未找到 OpenSSH 客户端', 'OpenSSH client not found on this computer'],
    ['登录节点当前无法联系 Slurm 控制器', 'The login node cannot reach the Slurm controller'],
    ['系统凭据存储不可用，无法完成首次公钥部署', 'System credentials are unavailable; initial public-key installation cannot complete'],
    ['终端已打开；复制命令、粘贴后按 Return', 'Terminal opened; copy and paste the command, then press Return'],
    ['本地配置保存失败', 'Could not save local settings'], ['本地配置保存失败；已撤销本次配置修改', 'Could not save local settings; this change was reverted'],
    ['本地配置已恢复，服务器原有公钥内容未改变', 'Local settings restored; existing server public keys were unchanged'],
    ['本地配置已恢复；为避免覆盖 authorized_keys 的并发修改，已验证的新增公钥和本地密钥被保留，请重试保存或人工处理', 'Local settings restored; verified keys were retained to avoid overwriting concurrent authorized_keys changes. Retry saving or recover manually.'],
    ['本地配置恢复未完成，当前状态需要人工确认', 'Local settings recovery did not complete; review the current state manually'],
    ['本地配置恢复未完成；密钥已保留，请按诊断信息人工检查', 'Local settings recovery did not complete; keys were retained. Review the diagnostics manually.'],
    ['校验期间服务器配置已变化，请重新展开', 'Server configuration changed during validation; collapse and expand again'],
    ['没有可导入的服务器设置文件', 'No server configuration file available to import'],
    ['等待文件夹读取超时，请重试', 'Folder loading timed out; retry'],
    ['缺少服务器标识', 'Missing server identifier'], ['置顶服务器数量已达到上限', 'Pinned-server limit reached'],
    ['节点快照已经更新，请从第一页重新加载', 'Node snapshot changed; reload from the first page'],
    ['设置已被其他操作更新，请重新打开后再保存', 'Settings changed elsewhere; reopen before saving'],
    ['设置提交失败且原配置恢复未完成；请停止操作并重启应用检查配置', 'Settings submission and recovery failed; stop making changes and restart the app to review settings'],
    ['配置提交失败，且原配置恢复未完成；请停止操作并重启应用检查配置', 'Configuration submission and recovery failed; stop making changes and restart the app to review settings'],
    ['配置未保存，但系统凭据回滚失败，登录密码状态可能已变化。请立即在服务器设置中重新输入或删除该密码。', 'Settings were not saved, but credential rollback failed and the password may have changed. Re-enter or remove the password in server settings now.'],
    ['诊断范围无效', 'Invalid diagnostic scope'], ['请选择使用现有密钥或生成专用密钥', 'Choose an existing key or generate a dedicated key'],
    ['读取前服务器配置已变化，请重新展开', 'Server configuration changed before loading; collapse and expand again'],
    ['读取期间服务器配置已变化，请重新展开', 'Server configuration changed while loading; collapse and expand again'],
    ['这台服务器不是 Slurm 集群', 'This server is not a Slurm cluster'], ['这台服务器已停用', 'This server is disabled'],
    ['这台服务器已停用，请先恢复监控', 'This server is disabled; resume monitoring first'], ['这台服务器当前已暂停监控', 'Monitoring is paused for this server'],
    ['远端原有内容未改变；本地密钥已保留便于重试', 'Existing remote content was unchanged; the local key was retained for retry'],
    ['连接测试发生未知错误', 'Unexpected connection-test error'], ['连接测试成功', 'Connection test succeeded'],
    ['连接类型已自动识别并保存', 'Connection type detected and saved'], ['选择的 SSH 公钥格式无效', 'Invalid selected SSH public-key format'],
    ['部署 SSH 公钥时发生未知错误；为避免丢失可能已部署密钥，本地专用密钥已保留', 'Unexpected public-key installation error; the local key was retained because the public key may already be installed'],
    ['验证 SSH Key 时发生未知错误', 'Unexpected SSH key verification error'],
    ['为避免覆盖 authorized_keys 的并发修改，新增公钥和本地密钥已保留', 'Keys were retained to avoid overwriting concurrent authorized_keys changes'],
    ['为避免误删 authorized_keys 中其他程序的并发修改，新增公钥和本地密钥已保留，请修复认证后重试或人工删除该公钥', 'Keys were retained to protect concurrent authorized_keys changes; fix authentication and retry, or remove the exact public key manually'],
    ['服务器结果不确定，本地专用密钥已保留，便于重试或人工恢复', 'Server outcome is uncertain; the local key was retained for retry or manual recovery'],
    ['本地专用密钥清理失败，密钥已保留，请人工检查', 'Local key cleanup failed; the key was retained for manual review'],
    ['本地专用密钥清理失败，密钥已保留，请在设置中重试或人工删除', 'Local key cleanup failed; retry in Settings or remove the retained key manually'],
    ['所需单卡显存必须在 0 到 1000 GiB 之间', 'Required VRAM per GPU must be between 0 and 1000 GiB'],
    ['所需单卡显存必须是数字', 'Required VRAM per GPU must be numeric'],
    ['服务器启用状态必须是布尔值', 'Server enabled state must be boolean'], ['服务器地址格式无效', 'Invalid server address'],
    ['服务器密码不能包含换行或 NUL 字符', 'Server password cannot contain newlines or NUL characters'], ['服务器密码过长', 'Server password is too long'],
    ['服务器目录位置只能是左侧或右侧', 'Server navigation must be positioned left or right'],
    ['分页位置必须是整数', 'Page offset must be an integer'], ['每页数量必须是整数', 'Page size must be an integer'],
    ['节点快照版本必须是整数', 'Node snapshot revision must be an integer'], ['刷新目录参数必须是布尔值', 'Directory refresh option must be boolean'],
    ['收藏状态必须是布尔值', 'Favorite state must be boolean'], ['置顶状态必须是布尔值', 'Pinned state must be boolean'],
    ['监控暂停状态必须是布尔值', 'Monitoring pause state must be boolean'], ['提示标识无效', 'Invalid notice identifier'],
    ['收藏 GPU 数量已达到上限', 'GPU favorites limit reached'], ['收藏服务器数量已达到上限', 'Server favorites limit reached'],
    ['同一服务器不能同时重命名为多个 ID', 'A server cannot be renamed to multiple IDs at once'],
    ['密码更新引用了不存在的服务器', 'Password update references a missing server'],
    ['服务器重命名后不能继续保留旧 ID', 'A renamed server cannot retain its old ID'],
    ['服务器重命名引用了不存在的新 ID', 'Server rename references a missing new ID'],
    ['服务器重命名引用了不存在的旧 ID', 'Server rename references a missing old ID'],
    ['展开目录不能为空', 'Expanded directory cannot be empty'], ['默认展开目录', 'Default expanded directory'],
    ['GPU 进程数据格式暂时无法识别；显存数据仍会正常刷新。', 'GPU process data could not be parsed; VRAM readings will continue to refresh.'],
    ['当前驱动未提供 GPU 进程快照；显存数据仍会正常刷新。', 'The driver does not provide GPU process snapshots; VRAM readings will continue to refresh.'],
    ['Host Key 已保存，服务器连接和资源读取成功', 'Host key saved; server connection and resource collection succeeded'],
    ['OpenSSH 配置文件不存在或不可读取', 'OpenSSH configuration does not exist or cannot be read'],
    ['OpenSSH 配置格式或权限无效，请先在终端检查该配置', 'Invalid OpenSSH configuration or permissions; check the configuration in a terminal'],
    ['PowerShell 已打开；复制命令、粘贴后按 Enter', 'PowerShell opened; copy and paste the command, then press Enter'],
    ['ProxyJump 配置无效，请检查跳板别名和循环引用', 'Invalid ProxyJump configuration; check jump-host aliases and circular references'],
    ['Release 缺少可验证的安装资产，已打开下载页面', 'The release has no verifiable installer; the download page was opened'],
    ['SSH Key 配置参数无效', 'Invalid SSH key setup parameters'],
    ['SSH Key 配置未完成；为保护 authorized_keys，密钥已安全保留，请重试或复制诊断后人工检查', 'SSH key setup did not complete. Keys were retained to protect authorized_keys; retry or copy diagnostics for manual review.'],
    ['SSH Key、ssh-agent 或用户名', 'SSH key, ssh-agent, or username'],
    ['SSH 和 Slurm 已连接，但没有识别到任何 GPU GRES；请检查 sinfo 输出和 GRES 配置', 'SSH and Slurm connected, but no GPU GRES were identified; check sinfo output and GRES configuration'],
    ['SSH 尝试了过多身份；请指定正确私钥或清理 ssh-agent 中无关密钥', 'SSH tried too many identities; select the correct private key or remove unrelated keys from ssh-agent'],
    ['SSH 已连接到交互式网关，但它不允许直接执行监控命令；请让 SSH Host/ProxyJump 最终落到 Slurm 登录节点', 'SSH reached an interactive gateway that cannot execute monitoring commands; configure Host/ProxyJump to reach the Slurm login node'],
    ['SSH 已连接并通过认证，但当前服务器类型缺少所需命令；集群登录节点请检查是否应选择 Slurm', 'SSH authenticated, but commands required by this backend are missing; cluster login nodes may require the Slurm backend'],
    ['SSH 已连接，但当前账号无权执行资源检测命令', 'SSH connected, but the account cannot execute resource discovery commands'],
    ['SSH 已连接，但服务器环境检测命令执行失败', 'SSH connected, but environment discovery failed'],
    ['SSH 已连接，但远端没有启动 Slurm 采集协议；常见原因是公共平台/ForceCommand 交互菜单、必须二次跳转，或账号禁止直接执行远程命令', 'SSH connected, but the Slurm collector did not start. Possible causes include an interactive gateway/ForceCommand menu, a required second hop, or restrictions on remote commands.'],
    ['SSH 查询失败', 'SSH query failed'],
    ['SSH 私钥文件不存在或不可读取', 'SSH private key does not exist or cannot be read'],
    ['SSH 私钥权限过宽，请限制为仅当前用户可读', 'SSH private-key permissions are too broad; restrict access to the current user'],
    ['SSH 私钥格式无效或无法由当前 OpenSSH 读取', 'SSH private-key format is invalid or unsupported by this OpenSSH version'],
    ['SSH 私钥需要口令，请先在系统 ssh-agent/钥匙串中解锁该密钥', 'The SSH private key requires a passphrase; unlock it in ssh-agent or the system keychain first'],
    ['SSH 跳板或代理转发失败，请先单独验证跳板连接', 'SSH jump-host or proxy forwarding failed; verify the jump-host connection separately'],
    ['SSH 连接和身份验证成功', 'SSH connection and authentication succeeded'], ['SSH 连接被中途重置', 'SSH connection was reset'],
    ['ssh-agent 拒绝使用该密钥，请重新解锁或重新加入密钥', 'ssh-agent refused the key; unlock or add the key again'],
    ['authorized_keys 在配置期间被其他程序修改；为避免覆盖，已停止本次操作，请重试', 'authorized_keys changed during setup; the operation stopped to avoid overwriting concurrent changes. Retry setup.'],
    ['公钥已仅追加写入 authorized_keys，未替换现有内容；私钥未传输', 'Public key appended to authorized_keys without replacing existing content; the private key was not transferred'],
    ['公钥已写入，但所选私钥验证失败；如私钥带口令，请先加载 ssh-agent', 'Public key installed, but private-key verification failed; load passphrase-protected keys into ssh-agent first'],
    ['另一台服务器正在核验 Host Key，请稍后再试', 'Another host-key check is in progress; try again shortly'],
    ['另一台服务器正在配置 SSH Key，请等待完成后再试', 'Another SSH key setup is in progress; wait for it to finish'],
    ['另一项设置正在保存，请稍后再导入服务器', 'Settings are being saved; import servers after saving finishes'],
    ['另一项设置正在保存，请稍后重试', 'Settings are being saved; try again shortly'],
    ['另一项设置正在保存，请等待完成后再配置 SSH Key', 'Settings are being saved; wait before configuring an SSH key'],
    ['启用自动同步前必须选择有效的服务器设置文件', 'Select a valid server configuration file before enabling automatic sync'],
    ['命令不存在，或 Slurm 只在交互式 module/.bashrc 环境中加入 PATH', 'Command missing, or Slurm is added to PATH only by interactive module/.bashrc setup'],
    ['处理本地 SSH Key 时发生未知错误', 'Unexpected error while handling the local SSH key'],
    ['尚未检测到可下载的新版本', 'No downloadable update detected'],
    ['已保存的服务器密码不存在，请先在登录与高级设置中重新保存', 'No saved server password; save it again in sign-in and advanced settings'],
    ['已切换为 SSH Key 优先；已保存的密码仅在密钥被拒绝时本地回退', 'SSH keys are now preferred; the saved password is used locally only if key authentication is rejected'],
    ['已安全复用此前生成的 VRAM Radar 专用密钥', 'Safely reused the existing dedicated VRAM Radar key'],
    ['已强制使用所选私钥完成一次独立 SSH 登录', 'Verified a separate SSH sign-in using only the selected private key'],
    ['已打开日志文件夹', 'Log folder opened'], ['已打开服务器终端', 'Server terminal opened'],
    ['已核对本地私钥和公钥；私钥不会离开这台电脑', 'Local key pair checked; the private key stays on this computer'],
    ['已生成并保护 VRAM Radar 专用 Ed25519 密钥', 'Dedicated VRAM Radar Ed25519 key generated and protected'],
    ['已自动识别为 SSH 直连', 'Direct SSH detected automatically'], ['已自动识别为 Slurm', 'Slurm detected automatically'],
    ['已识别连接类型，但保存失败', 'Connection type identified, but saving failed'], ['已读取服务器配置', 'Server configuration loaded'],
    ['已验证连接类型，但保存失败', 'Connection type verified, but saving failed'],
    ['当前 SSH Key 无法登录，且没有已保存的服务器密码；请先保存一次登录密码，或请管理员添加公钥', 'SSH key sign-in failed and no password is stored; save a sign-in password or ask an administrator to install the public key'],
    ['当前安装缺少安全密码助手，请重新安装 VRAM Radar', 'The secure password helper is missing; reinstall VRAM Radar'],
    ['当前平台暂不支持应用内安装', 'In-app installation is not supported on this platform'],
    ['当前桌面平台暂不支持自动打开终端，请复制 SSH 命令', 'Automatic terminal launch is unavailable on this platform; copy the SSH command'],
    ['当前没有可安装的新版本', 'No installable update available'], ['当前没有在线资源池满足这些条件', 'No online resource pool matches these requirements'],
    ['当前版本不支持一键更新', 'This version does not support one-click updates'],
    ['当前用户无权读取 SSH 私钥，请检查文件所有者和权限', 'The current user cannot read the SSH private key; check ownership and permissions'],
    ['当前网络无法到达服务器', 'The server is unreachable from this network'],
    ['当前账号被站点策略限制读取该类 Slurm 信息', 'Site policy prevents this account from reading this Slurm information'],
    ['找不到这个保存视图', 'Saved view not found'], ['找不到这台已保存的服务器', 'Saved server not found'], ['找不到这台服务器', 'Server not found'],
    ['文件夹读取未完成，请重试', 'Folder loading did not complete; retry'],
    ['无法从系统凭据存储读取服务器密码', 'Could not read the server password from system credentials'],
    ['无法使用当前 SSH 配置登录；请先保存一次服务器密码，或请管理员添加公钥', 'Cannot sign in with the current SSH configuration; save a server password or ask an administrator to install the public key'],
    ['无法保存 SSH Key 配置；本地配置已恢复，远端原有内容未改变', 'Could not save SSH key settings; local settings were restored and existing remote content was unchanged'],
    ['无法打开 GitHub Release 页面', 'Could not open the GitHub Release page'],
    ['无法打开命令窗口，请按教程中的搜索步骤手动打开', 'Could not open a terminal; follow the guide to open one manually'],
    ['无法打开日志文件夹', 'Could not open the log folder'],
    ['无法打开服务器终端，请复制 SSH 命令后手动运行', 'Could not open the server terminal; copy and run the SSH command manually'],
    ['无法解析服务器地址', 'Could not resolve the server address'],
    ['无法访问系统凭据存储，请检查钥匙串或凭据管理器', 'Could not access system credentials; check Keychain or Credential Manager'],
    ['无法读取账号文件夹结构', 'Could not read account folder structure'],
    ['更新下载验证失败', 'Update download verification failed'],
    ['更新包已通过 SHA-256 校验，并已在 Finder 中显示', 'Update package passed SHA-256 verification and was revealed in Finder'],
    ['更新已准备完成', 'Update ready'], ['更新已校验，应用即将关闭并自动重启', 'Update verified; the app will close and restart'],
    ['服务器 Host Key 已变化，请人工核对指纹', 'Server host key changed; verify its fingerprint manually'],
    ['服务器 Host Key 无法自动保存或验证，请检查 known_hosts 权限与 SSH 配置', 'Could not save or verify the host key; check known_hosts permissions and SSH settings'],
    ['服务器 Slurm 版本或站点命令包装与当前查询参数不兼容', 'The Slurm version or site command wrapper is incompatible with these query parameters'],
    ['服务器不存在', 'Server does not exist'], ['服务器密码不能为空', 'Server password cannot be empty'],
    ['服务器密码不存在，请在本地配置中重新输入', 'Server password not found; enter it again in local settings'],
    ['服务器密码不可用，请在本地配置中重新保存', 'Server password unavailable; save it again in local settings'],
    ['服务器拒绝 SSH 连接', 'Server refused the SSH connection'], ['服务器查询超时', 'Server query timed out'],
    ['服务器没有返回可验证的 SSH Key 结果', 'Server did not return a verifiable SSH key result'],
    ['服务器没有返回可验证的公钥安装结果，未更新本地配置', 'Server did not return a verifiable key-installation result; local settings were not updated'],
    ['服务器主目录不安全，已停止修改 authorized_keys', 'Server home directory is unsafe; authorized_keys modification stopped'],
    ['服务器已存在同一公钥，未重复写入', 'The public key already exists on the server; no duplicate was added'],
    ['服务器拒绝写入 SSH 公钥，请检查主目录权限或联系管理员', 'Server refused public-key installation; check home-directory permissions or contact an administrator'],
    ['服务器原本已有同一公钥，未改动远端内容；本地密钥已保留便于重试', 'The public key already existed; remote content was unchanged and the local key was retained for retry'],
    ['服务器的 .ssh 目录所有者或权限不安全，或是符号链接', 'Server .ssh directory has unsafe ownership/permissions or is a symbolic link'],
    ['服务器的 authorized_keys 所有者或权限不安全、不是普通文件，或是符号链接', 'Server authorized_keys has unsafe ownership/permissions, is not a regular file, or is a symbolic link'],
    ['服务器配置保存失败', 'Could not save server configuration'],
    ['服务器配置未能完整保存，已恢复原配置', 'Server configuration was not fully saved; previous settings were restored'],
    ['服务器配置版本缺失或已经变化，请重新打开设置', 'Configuration revision is missing or changed; reopen Settings'],
    ['未发现 servers.toml 或 OpenSSH config；请按下方教程查找后手动输入路径', 'No servers.toml or OpenSSH config found; follow the guide below and enter the path manually'],
    ['未发现默认 servers.toml，可手动输入文件地址', 'Default servers.toml not found; enter a path manually'],
    ['未命名进程', 'Unnamed process'], ['未找到 PowerShell。请按 Windows 键，搜索并打开 PowerShell', 'PowerShell not found. Press the Windows key, search for PowerShell, and open it.'],
    ['未自动重写 authorized_keys；新增公钥和本地密钥已保留，需重试或人工处理', 'authorized_keys was not rewritten automatically; the added public key and local key were retained for retry or manual recovery'],
    ['未自动重写 authorized_keys；请重试或人工检查新增公钥', 'authorized_keys was not rewritten automatically; retry or review the added public key manually'],
    ['· 已安全截断', '· Safely truncated'],
    ['· 已截断', '· Truncated'],
    ['正在识别当前账号。', 'Identifying the current account.'],
    ['进程较多，部分用户与时间详情将在后续刷新中补齐。', 'Additional ownership and timing details will be loaded in subsequent refreshes.'],
    ['GPU 采集器', 'GPU collector'],
    ['OpenSSH 别名与主机地址至少填写一个', 'Enter an OpenSSH alias or host address.'],
    ['PowerShell SSH 命令已复制', 'PowerShell SSH command copied'],
    ['SSH Key 优先，密码仅在认证失败时回退', 'Prefer SSH keys; use the password only if authentication fails'],
    ['SSH Key 优先，新密码仅作本地回退', 'Prefer SSH keys; keep the new password as a local fallback'],
    ['SSH Key 配置未完成', 'SSH key setup is incomplete'],
    ['SSH 免密登录已就绪', 'Passwordless SSH is ready'],
    ['SSH 免密登录已配置并验证', 'Passwordless SSH configured and verified'],
    ['SSH 命令已复制到剪贴板', 'SSH command copied to clipboard'],
    ['Slurm GPU 调度状态', 'Slurm GPU scheduler'],
    ['Slurm 调度器', 'Slurm scheduler'],
    ['不限时', 'Unlimited'],
    ['从未成功', 'Never succeeded'],
    ['作业内存不足', 'Job out of memory'],
    ['保存后将删除系统凭据', 'The stored credential will be removed when saved'],
    ['保存后将更新系统凭据', 'The stored credential will be updated when saved'],
    ['保存后恢复 ssh-agent 或私钥登录', 'Saving restores ssh-agent or private-key sign-in'],
    ['偏低', 'Low'], ['充足', 'Healthy'], ['紧张', 'Limited'],
    ['其他 ·', 'Other ·'], ['准备', 'Preparing'], ['准备中', 'Preparing'],
    ['分区默认', 'Partition default'], ['刚刚更新', 'Updated just now'],
    ['可用显存未知', 'Free VRAM unknown'], ['右侧', 'Right'], ['左侧', 'Left'],
    ['后台读取中…界面仍可操作', 'Loading in background…you can continue using the interface'],
    ['命令已复制到剪贴板', 'Command copied to clipboard'], ['命令窗口已打开', 'Terminal opened'],
    ['在导航中只看收藏', 'Show only favorites in navigation'], ['复制 SSH 命令', 'Copy SSH command'],
    ['复制失败', 'Copy failed'], ['失败', 'Failed'], ['安全阻止', 'Blocked for safety'],
    ['完整 SSH 命令已复制（地址、用户与端口已包含）', 'Full SSH command copied, including host, user, and port'],
    ['将从官方 GitHub Release 下载并校验安装包。校验成功后应用会关闭、安装并自动重启；失败时保留当前版本。是否继续？', 'Download and verify the installer from the official GitHub Release? After verification, the app will close, install, and restart. The current version is retained if verification fails.'],
    ['将从官方 GitHub Release 下载并校验更新包。校验成功后会在 Finder 中显示，仍需你手动替换应用。是否继续？', 'Download and verify the update from the official GitHub Release? After verification, Finder will show the package so you can replace the app manually.'],
    ['将使用系统凭据中保存的新密码', 'The new password stored in system credentials will be used'],
    ['展开更多', 'Show more'], ['工作目录路径', 'Working directory path'],
    ['已一键收起当前页面的全部内容', 'All sections on this page collapsed'],
    ['已使用', 'Used'], ['已停用', 'Disabled'], ['已分配（按整卡）', 'Allocated (whole GPUs)'],
    ['已单独关注该任务，结束时会提醒', 'Watching this task; you will be notified when it ends'],
    ['已取消', 'Cancelled'], ['已取消收藏', 'Removed from favorites'], ['已取消收藏 GPU', 'GPU removed from favorites'],
    ['已取消该任务的单独提醒', 'Individual alert removed for this task'],
    ['已固定', 'Pinned'], ['已复制', 'Copied'], ['已复制到剪贴板', 'Copied to clipboard'],
    ['已定位到所选服务器', 'Selected server located'], ['已恢复监控', 'Monitoring resumed'],
    ['已恢复自动定位', 'Automatic directory selection restored'],
    ['已收藏', 'Added to favorites'], ['已收藏 GPU', 'GPU added to favorites'], ['已收藏服务器', 'Server added to favorites'],
    ['已收起设置中的全部说明与高级选项', 'All help and advanced settings collapsed'],
    ['已暂停', 'Paused'], ['已暂停这台服务器', 'Monitoring paused for this server'],
    ['已移除全部单独关注任务', 'All individually watched tasks removed'],
    ['已读取', 'Loaded'], ['已达到用户任务上限', 'User job limit reached'],
    ['已验证；SSH Key 优先，保存的密码仅作回退', 'Verified; SSH keys preferred, with the stored password as fallback'],
    ['归属不可见', 'Ownership unavailable'], ['当前可见任务', 'Currently visible tasks'],
    ['当前已有匹配资源', 'Matching resources are available'],
    ['当前桌面组件不支持资源匹配，请重新安装最新版本', 'Resource matching is unavailable in this desktop component. Reinstall the latest version.'],
    ['当前没有可见的排队或运行中 GPU 任务', 'No visible queued or running GPU jobs'],
    ['当前没有排队或运行中的 GPU 任务', 'No queued or running GPU jobs'],
    ['当前没有满足条件的资源', 'No resources currently match'],
    ['当前版本无法生成 SSH 命令', 'This version cannot generate SSH commands'],
    ['当前版本暂不支持一键打开命令窗口', 'Opening a terminal is not supported in this version'],
    ['当前版本暂不支持保存视图', 'Saved views are not supported in this version'],
    ['当前版本暂不支持打开日志目录', 'Opening the log directory is not supported in this version'],
    ['当前版本暂不支持收藏 GPU', 'GPU favorites are not supported in this version'],
    ['当前版本暂不支持收藏服务器', 'Server favorites are not supported in this version'],
    ['当前版本暂不支持诊断导出', 'Diagnostic export is not supported in this version'],
    ['当前目录不可读取', 'This directory cannot be read'], ['当前筛选没有匹配的服务器', 'No servers match this filter'],
    ['当前默认', 'Current default'], ['总量待补充', 'Total not yet available'], ['恢复', 'Resume'], ['我的 GPU', 'My GPUs'],
    ['所有服务器尚未监控就绪', 'No servers are ready for monitoring yet'],
    ['所选时间范围内没有可显示的 GPU 终态任务', 'No completed GPU jobs to show in the selected period'],
    ['手动填写或检查', 'Enter or review manually'], ['打开服务器终端', 'Open server terminal'], ['打开终端', 'Open terminal'],
    ['按三个简单步骤完成第一台服务器配置，详细教程随时可以展开。', 'Set up your first server in three steps. Expand the detailed guide whenever needed.'],
    ['提醒检查失败，将在下次刷新重试', 'Alert check failed; retrying on the next refresh'],
    ['提醒设置保存失败', 'Could not save alert settings'], ['收尾中', 'Completing'],
    ['文件夹路径', 'Folder path'], ['文件路径', 'File path'],
    ['无法保存收藏', 'Could not save favorites'], ['无法保存服务器目录位置', 'Could not save navigator position'],
    ['无法保存视图', 'Could not save view'], ['无法保存默认目录', 'Could not save default directory'],
    ['无法关闭提示', 'Could not dismiss notice'], ['无法删除视图', 'Could not delete view'],
    ['无法恢复自动定位', 'Could not restore automatic directory selection'], ['无法打开命令窗口', 'Could not open terminal'],
    ['无法打开日志目录', 'Could not open log directory'], ['无法打开终端', 'Could not open terminal'],
    ['无法更新 GPU 收藏', 'Could not update GPU favorites'], ['无法更新服务器状态', 'Could not update server status'],
    ['无法更新监控状态', 'Could not update monitoring status'], ['无法生成 SSH 命令', 'Could not generate SSH command'],
    ['无法生成诊断', 'Could not generate diagnostics'], ['无法移除关注任务', 'Could not remove watched tasks'],
    ['无法访问剪贴板', 'Could not access clipboard'], ['无法访问剪贴板，请手动选择命令', 'Could not access clipboard; select the command manually'],
    ['无法读取文件夹结构', 'Could not load folder structure'], ['无法读取节点', 'Could not load nodes'],
    ['无法读取这个目录', 'Could not read this directory'], ['旧目录快照 ·', 'Previous directory snapshot ·'],
    ['显示名称不能为空', 'Display name cannot be empty'], ['暂时无法连接 GitHub', 'GitHub is temporarily unreachable'],
    ['服务器 ID 与前面的服务器重复（不区分大小写）', 'Server ID duplicates an earlier server (case-insensitive)'],
    ['服务器 ID 格式不正确', 'Invalid server ID format'],
    ['服务器地址、账号或密码有尚未保存的修改。请先保存设置，再配置 SSH Key。', 'Host, account, or password changes are unsaved. Save settings before configuring an SSH key.'],
    ['服务器连接类型已自动验证', 'Server connection type verified automatically'],
    ['未分区', 'No partition'], ['未收到配置结果', 'No setup result received'], ['未知', 'Unknown'], ['未知卡型', 'Unknown GPU model'], ['未记录', 'Not recorded'],
    ['正在刷新', 'Refreshing'], ['正在刷新 ·', 'Refreshing ·'], ['正在建立首次有效快照', 'Creating the first valid snapshot'],
    ['正在本地查找用户、系统、编辑器和便携式 SSH 配置…', 'Searching local user, system, editor, and portable SSH configurations…'],
    ['正在核对本地密钥、部署公钥并验证登录…', 'Checking local keys, installing the public key, and verifying sign-in…'],
    ['正在检查新条件', 'Checking new requirements'], ['正在检查更新', 'Checking for updates'], ['正在检查更新…', 'Checking for updates…'],
    ['正在检查条件', 'Checking requirements'], ['正在测试已保存的连接配置…', 'Testing the saved connection settings…'],
    ['正在读取并解析本地配置…', 'Reading and parsing local configuration…'], ['正在读取服务器…', 'Loading servers…'],
    ['没有可复制的命令', 'No command to copy'], ['没有可复制的诊断内容', 'No diagnostics to copy'],
    ['生成独立密钥，部署后自动验证', 'Generate a dedicated key and verify it after installation'],
    ['登录密码已安全保存在系统凭据库', 'Sign-in password saved securely in system credentials'],
    ['监控已恢复', 'Monitoring resumed'], ['监控已暂停', 'Monitoring paused'],
    ['目录缓存状态已失效，请重新展开', 'Directory cache expired; collapse and expand again'],
    ['端口必须在 1 到 65535 之间', 'Port must be between 1 and 65535'],
    ['等待下一次刷新获取 GPU 进程。', 'GPU processes will be loaded on the next refresh.'],
    ['等待依赖任务', 'Waiting for dependencies'], ['等待分配', 'Awaiting allocation'], ['等待满足条件', 'Waiting for matching resources'],
    ['等待调度优先级', 'Waiting for scheduling priority'], ['等待配置', 'Awaiting configuration'], ['筛选后的 GPU 节点', 'Filtered GPU nodes'],
    ['筛选视图已保存', 'Filter view saved'], ['筛选视图已删除', 'Filter view deleted'], ['系统凭据中已有密码', 'Password stored in system credentials'],
    ['缓存已校验', 'Cache verified'], ['缓存待深校验', 'Cache awaiting full validation'],
    ['节点状态已更新，已返回第一页', 'Node state changed; returned to the first page'], ['节点状态已更新，请重新读取', 'Node state changed; reload nodes'],
    ['设备', 'Device'], ['诊断已复制到剪贴板，可直接粘贴给维护者', 'Diagnostics copied; paste them in your support request'],
    ['请先保存这台服务器，再测试连接。', 'Save this server before testing the connection.'],
    ['请先保存这台服务器，再配置 SSH 免密登录。', 'Save this server before configuring passwordless SSH.'],
    ['请先填写视图名称', 'Enter a view name first'], ['请在设置中保存服务器启用状态', 'Save server monitoring preferences in Settings'],
    ['请求节点暂不可用', 'Requested nodes are temporarily unavailable'], ['请选择现有私钥路径。', 'Select an existing private-key path.'],
    ['读取失败', 'Loading failed'], ['账号主目录', 'Account home directory'], ['账号识别中', 'Identifying account'], ['超时', 'Timed out'],
    ['过去 24 小时内没有可见的 GPU 终态任务', 'No visible completed GPU jobs in the past 24 hours'],
    ['过去 24 小时内没有我的可见 GPU 终态任务', 'No visible completed GPU jobs for my account in the past 24 hours'],
    ['这份旧快照尚未包含 GPU 进程；下一次成功刷新后会自动补充。', 'This older snapshot has no GPU process details; they will be added after the next successful refresh.'],
    ['这台服务器', 'This server'], ['进程信息不可用', 'Process information unavailable'],
    ['连接信息有尚未保存的修改，请先保存后再验证当前配置。', 'Connection changes are unsaved. Save them before verifying the configuration.'],
    ['连接测试未通过', 'Connection test failed'], ['连接测试通过', 'Connection test passed'],
    ['配置已保存，正在连接服务器', 'Configuration saved; connecting to servers'],
    ['配置已在其他操作中更新；最新版本已载入，当前表单未覆盖，请核对后重新保存。', 'Configuration changed elsewhere. The latest version was loaded without overwriting your form; review it and save again.'],
    ['配置异常', 'Configuration error'], ['链接 ·', 'Link ·'], ['首次使用引导', 'First-time setup'],
    ['默认展开目录已保存', 'Default expanded directory saved'],
    ['；多来源导入不会绑定单一文件自动同步', '; importing multiple sources does not enable automatic sync with a single file'],
    ["CPU 指标说明", "CPU metric reference"],
    ["CPU 使用率：表示最近一次采样区间内，主机全部逻辑 CPU 处于非空闲状态的时间占比。该指标反映整台主机的总体活动程度，不代表某个进程的 CPU 使用率，也不等同于 GPU 利用率。", "CPU utilization: the share of non-idle time across the host’s logical CPUs during the latest sampling interval. It describes overall host activity, not the CPU usage of an individual process or GPU utilization."],
    ["系统负载：1、5、15 分钟数值分别表示对应时间窗口内，正在运行、等待 CPU 调度或处于不可中断等待状态的平均任务数量。负载是任务数量而非百分比；较高负载可能来自计算需求，也可能来自 I/O 等待。", "System load: the 1, 5 and 15 minute values represent the average number of tasks running, waiting for CPU scheduling or in uninterruptible sleep over those windows. Load is a task count, not a percentage; elevated load may reflect computational demand or I/O waits."],
    ["核心数量与负载判断：物理核心表示处理器的实际计算核心，逻辑核心表示操作系统可调度的执行单元，启用 SMT 或超线程后两者可能不同。可将负载与逻辑核心数结合观察，例如 16 个逻辑核心对应负载 16，表示平均任务数量与可调度单元数相当；是否存在瓶颈仍需结合 CPU 使用率、I/O 和持续时间判断。", "Core counts and interpretation: physical cores are hardware compute cores; logical CPUs are execution units available to the operating system and may include SMT or Hyper-Threading. Compare load with logical CPU count: on a host with 16 logical CPUs, load 16 means the average task count equals the number of schedulable units. Assess bottlenecks using CPU utilization, I/O activity and the duration of the condition together."],
    ["主机内存：此处统计系统 RAM，不包含 GPU 显存。可用内存优先采用内核提供的 MemAvailable，包含预计可回收的部分缓存；因此，可用内存不等于完全未使用的内存。容量以 GiB 为单位，1 GiB 等于 2³⁰ 字节。", "Host memory: these values describe system RAM, excluding GPU VRAM. Available memory uses the kernel’s MemAvailable value when provided and includes some reclaimable cache; it is not identical to completely unused memory. Capacity is reported in GiB, where 1 GiB equals 2³⁰ bytes."],
    ["数据时效与缺失值：各项指标来自最近一次服务器采样，不能视为连续实时测量。连接中断或数据过期时，请结合卡片上的最后成功时间判断；旧快照仅供参考。未采集到的指标不应按零值理解。", "Freshness and missing values: metrics come from the latest server sample and are not continuous real-time measurements. When the connection is interrupted or data becomes stale, refer to the card’s last successful sample time; cached values are for reference only. An unavailable metric must not be interpreted as zero."],

    ['显存雷达', 'VRAM Radar'],
    ['欢迎使用显存雷达', 'Welcome to VRAM Radar'],
    ['先添加一台 GPU 服务器', 'Add your first GPU server'],
    ['自动查找本机 SSH 配置，确认连接方式后开始监控。', 'Discover local SSH configuration, confirm the connection, and start monitoring.'],
    ['首次配置说明', 'First-time setup'],
    ['自动发现', 'Auto-discover'],
    ['检查登录方式', 'Review sign-in'],
    ['保存并开始监控', 'Save and monitor'],
    ['开始配置', 'Start setup'],
    ['没有 SSH 配置也没关系，向导内有 Windows 和 macOS 的完整教程。', 'No SSH configuration yet? The guide includes complete Windows and macOS instructions.'],
    ['GPU 资源总览', 'GPU overview'],
    ['当前可用显存', 'Currently available VRAM'],
    ['所有监控就绪 GPU 合计', 'Across all monitored GPUs'],
    ['可用比例', 'Available capacity'],
    ['监控就绪', 'Monitoring ready'],
    ['SSH 已认证 / 资源已读取', 'SSH authenticated / resources loaded'],
    ['已读取 GPU', 'GPUs loaded'],
    ['块', ' GPUs'],
    ['仅统计当前有效快照', 'Current valid snapshots only'],
    ['可用显存、卡型与任务状态', 'Available VRAM, GPU models, and jobs'],
    ['GPU 概览', 'GPU overview'],
    ['帮我找一台可用 GPU', 'Find available GPUs'],
    ['按卡数、单卡空闲显存、卡型与分区筛选', 'Filter by GPU count, free VRAM per GPU, model, and partition'],
    ['填写需求', 'Set requirements'],
    ['收起', 'Collapse'],
    ['已保存的资源筛选', 'Saved resource filters'],
    ['GPU 数量', 'GPU count'],
    ['单卡最低空闲显存', 'Minimum free VRAM per GPU'],
    ['卡型（可选）', 'GPU model (optional)'],
    ['例如 4090、A100', 'e.g. 4090 or A100'],
    ['更多条件', 'More filters'],
    ['分区、同节点与结果数量', 'Partition, same-node placement, and result count'],
    ['展开', 'Expand'],
    ['编辑', 'Edit'],
    ['分区（可选）', 'Partition (optional)'],
    ['例如 gpu-large', 'e.g. gpu-large'],
    ['显示结果', 'Results'],
    ['前 3 个', 'Top 3'],
    ['前 5 个', 'Top 5'],
    ['前 10 个', 'Top 10'],
    ['多张 GPU 必须在同一节点', 'Place multiple GPUs on one node'],
    ['查找可用资源', 'Find resources'],
    ['本次运行有资源时提醒我', 'Notify me when this app finds a match'],
    ['保存这组条件', 'Save these filters'],
    ['下次一键恢复', 'Reuse them next time'],
    ['保存', 'Save'],
    ['例如 8×H100', 'e.g. 8×H100'],
    ['保存视图', 'Save view'],
    ['服务器状态', 'Server status'],
    ['展开查看 GPU、进程和任务', 'Expand to inspect GPUs, processes, and jobs'],
    ['正在读取', 'Loading'],
    ['服务器内容显示方式', 'Server content display'],
    ['一键收起', 'Collapse all'],
    ['上一页', 'Previous'],
    ['下一页', 'Next'],
    ['服务器快速导航', 'Quick server navigation'],
    ['服务器目录在右侧，拖动或按回车移到左侧', 'Server navigator is on the right. Drag it or press Enter to move it left.'],
    ['拖动到左侧或右侧', 'Drag left or right'],
    ['服务器', 'Servers'],
    ['名称、卡型、分区', 'Name, model, partition'],
    ['搜索服务器', 'Search servers'],
    ['筛选服务器', 'Filter servers'],
    ['全部', 'All'],
    ['空闲', 'Available'],
    ['任务', 'Jobs'],
    ['异常', 'Issues'],
    ['收藏', 'Favorites'],
    ['没有匹配的服务器', 'No matching servers'],
    ['上一台服务器', 'Previous server'],
    ['上一台', 'Previous'],
    ['当前筛选位置', 'Current filtered position'],
    ['回到本机', 'Back to this host'],
    ['收起模块', 'Collapse modules'],
    ['整台', 'Whole'],
    ['仅 GPU', 'GPU only'],
    ['收藏整台', 'Favorite whole server'],
    ['含收藏卡', 'Has favorite GPUs'],
    ['还没有收藏', 'No favorites yet'],
    ['收藏这台服务器', 'Favorite this server'],
    ['取消收藏这台服务器', 'Unfavorite this server'],
    ['只看收藏 GPU', 'Favorite GPUs only'],
    ['显示全部 GPU', 'Show all GPUs'],
    ['当前没有收藏的 GPU', 'No favorited GPUs on this server'],
    ['当前不是正式安装版，无法应用内更新，将打开 GitHub 发布页', 'This is not a formal installed build, so in-app update is unavailable. Opening the GitHub releases page.'],
    ['当前不是 Windows 安装版', 'Not a Windows installed build'],
    ['当前程序文件名不受自动更新支持', 'This executable name does not support automatic updates'],
    ['当前不是由正式安装器安装的版本', 'This build was not installed by the formal installer'],
    ['此版本缺少更新执行器', 'This build is missing the update helper'],
    ['已收起该服务器的模块', 'Collapsed modules on this server'],
    ['当前服务器没有展开的模块', 'No open modules on this server'],
    ['下一台服务器', 'Next server'],
    ['下一台', 'Next'],
    ['设置', 'Settings'],
    ['暂停监控', 'Pause monitoring'],
    ['恢复监控', 'Resume monitoring'],
    ['正在初始化', 'Initializing'],
    ['立即刷新', 'Refresh now'],
    ['设置与服务器', 'Settings and servers'],
    ['本地配置', 'Local configuration'],
    ['先用自动发现完成常见设置，需要时再展开登录与高级选项。', 'Start with auto-discovery, then expand sign-in and advanced options only when needed.'],
    ['设置内容显示方式', 'Settings content display'],
    ['关闭设置', 'Close settings'],
    ['首次配置进度', 'First-time setup progress'],
    ['了解用途', 'Overview'],
    ['先知道它会做什么', 'See what the app does'],
    ['发现服务器', 'Discover servers'],
    ['自动查找或打开教程', 'Discover automatically or open the guide'],
    ['检查并完成', 'Review and finish'],
    ['确认连接与登录方式', 'Confirm connection and sign-in'],
    ['约 1 分钟完成', 'About one minute'],
    ['集中查看每台服务器的 GPU 状态', 'See every server and GPU in one place'],
    ['集中查看 GPU 显存、进程和 Slurm 任务。', 'Monitor GPU memory, processes, and Slurm jobs together.'],
    ['可用显存', 'Available VRAM'],
    ['先看容量与卡型', 'Check capacity and GPU model first'],
    ['任务详情', 'Job details'],
    ['再展开进程和 Slurm', 'Expand processes and Slurm when needed'],
    ['本机配置', 'Local-only settings'],
    ['密码保存在系统凭据库', 'Passwords stay in the system credential store'],
    ['显示与刷新', 'Display and refresh'],
    ['界面与提醒', 'Interface and alerts'],
    ['界面、提醒与更新', 'Interface, alerts, and updates'],
    ['语言、刷新、任务提醒和版本检查', 'Language, refresh, task alerts, and update checks'],
    ['语言、刷新、关闭方式和收藏通知', 'Language, refresh, close behavior, and favorite alerts'],
    ['这些选项只影响这台电脑上的监控界面。', 'These options affect only the monitoring interface on this computer.'],
    ['仅本机', 'This computer only'],
    ['配置名称', 'Profile name'],
    ['刷新间隔（秒）', 'Refresh interval (seconds)'],
    ['界面语言', 'Interface language'],
    ['简体中文', 'Simplified Chinese'],
    ['点击关闭按钮时', 'When the close button is clicked'],
    ['收起到通知区域', 'Minimize to the notification area'],
    ['直接退出应用', 'Exit the app'],
    ['收藏的服务器或指定 GPU 空闲时提醒我', 'Remind me when a favorited server or GPU is free'],
    ['我的任务结束时提醒', 'Notify me when my tasks finish'],
    ['默认提醒当前账号下的 Slurm 任务与 GPU 进程；也可在任务表中单独关注', 'Notify for this account’s Slurm jobs and GPU processes by default; individual tasks can also be watched.'],
    ['其他用户的任务不会自动关注；只提醒你在任务表中逐项选择的任务。', 'Other users’ tasks are never watched automatically; only tasks you select individually will notify you.'],
    ['单独关注完成提醒', 'Watch this task'],
    ['仅关注这个用户的这一项任务', 'Watch only this task from this user'],
    ['取消单独提醒', 'Stop watching this task'],
    ['已关注', 'Watching'],
    ['关注', 'Watch'],
    ['全部移除', 'Remove all'],
    ['通知中心', 'Notification center'],
    ['任务完成、版本更新与 GPU 可用消息', 'Task completion, updates, and GPU availability messages'],
    ['全部已读', 'Mark all read'],
    ['清空通知', 'Clear notifications'],
    ['通知已清空', 'Notifications cleared'],
    ['清空通知失败', 'Could not clear notifications'],
    ['暂无通知', 'No notifications yet'],
    ['打开通知中心', 'Open notification center'],
    ['任务完成', 'Task completed'],
    ['收藏空闲', 'Favorites free'],
    ['GPU 条件满足', 'GPU criteria matched'],
    ['版本更新', 'Update available'],
    ['应用通知', 'App notification'],
    ['任务已完成', 'Task completed'],
    ['收藏的资源已空闲', 'Favorited resources are free'],
    ['发现新版本', 'Update available'],
    ['已关注任务', 'Watched tasks'],
    ['只在任务结束时提醒', 'Notify only when a task finishes'],
    ['还没有关注任务', 'No watched tasks yet'],
    ['可在任务表中逐项关注。', 'Watch tasks individually from a task table.'],
    ['项', 'items'],
    ['移除', 'Remove'],
    ['收藏的资源已空闲。', 'Favorited resources are free.'],
    ['应用更新', 'App updates'],
    ['发现新版本后会进入通知中心', 'New versions appear in the notification center.'],
    ['安全一键更新', 'Safe one-click update'],
    ['下载并校验', 'Download and verify'],
    ['正在确认官方更新文件…', 'Confirming the official update…'],
    ['正在下载并校验更新…', 'Downloading and verifying the update…'],
    ['下载完成，正在准备安装…', 'Download complete. Preparing installation…'],
    ['更新已准备完成，应用即将重启', 'Update ready. The app will restart shortly.'],
    ['更新包已下载并通过校验', 'The update was downloaded and verified.'],
    ['更新失败，当前版本未被修改', 'Update failed. The current version was not changed.'],
    ['正在下载', 'Downloading'],
    ['已开始，请稍候…', 'Started. Please wait…'],
    ['无法读取更新进度', 'Unable to read update progress'],
    ['更新操作已结束', 'The update operation has finished'],
    ['更新操作未完成', 'The update operation did not complete'],
    ['查看更新', 'View update'],
    ['检查更新', 'Check for updates'],
    ['整卡空闲或达到设定显存时发送系统通知', 'Send a system notification when a GPU is idle or reaches the memory threshold'],
    ['单卡最低空闲显存（GiB，可选）', 'Minimum free VRAM per GPU (GiB, optional)'],
    ['留空：只提醒整卡空闲', 'Leave empty: notify only for idle GPUs'],
    ['诊断与日志', 'Diagnostics and logs'],
    ['连接异常时使用，复制内容会自动脱敏', 'Use when connections fail; copied details are automatically redacted'],
    ['复制脱敏诊断', 'Copy redacted diagnostics'],
    ['打开日志目录', 'Open log folder'],
    ['服务器发现与导入', 'Server discovery and import'],
    ['自动读取本机 SSH 配置；检测不到时再查看教程', 'Read local SSH configuration automatically; open the guide only when needed'],
    ['把你平时登录的 GPU 服务器加进来', 'Add the GPU servers you already use'],
    ['如果终端里已经能运行 ', 'If your terminal can already run '],
    ['如果终端里已经能运行', 'If your terminal can already run'],
    ['，进入这一步就会自动查找。', ', this step will discover it automatically.'],
    ['服务器导入步骤', 'Server import steps'],
    ['本地扫描 SSH 配置，不连接服务器', 'Scan local SSH configuration without connecting'],
    ['检查类型', 'Review type'],
    ['确认每台服务器是 SSH 直连还是 Slurm', 'Confirm direct SSH or Slurm for each server'],
    ['保存并查看', 'Save and view'],
    ['密码可选，只保存在系统凭据库', 'Passwords are optional and stored only in the system credential store'],
    ['服务器设置文件路径', 'Server configuration file'],
    ['servers.toml 或 ~/.ssh/config', 'servers.toml or ~/.ssh/config'],
    ['启动时自动同步此文件', 'Sync this file at startup'],
    ['自动发现并导入', 'Discover and import'],
    ['导入并替换列表', 'Import and replace list'],
    ['只读取本机服务器别名；不执行配置命令，不连接服务器，不读取私钥、密码或 ', 'Reads only local server aliases. It does not run configuration commands, connect to servers, or read private keys, passwords, or '],
    ['只读取本机服务器别名；不执行配置命令，不连接服务器，不读取私钥、密码或', 'Reads only local server aliases. It does not run configuration commands, connect to servers, or read private keys, passwords, or'],
    ['自动检测不到？', 'Nothing discovered?'],
    ['按 Windows 或 macOS 教程找到 SSH 配置，命令可一键复制', 'Follow the Windows or macOS guide to find SSH configuration and copy commands in one click'],
    ['展开教程', 'Open guide'],
    ['先弄清楚要找什么', 'What you are looking for'],
    ['SSH 配置通常是一个名为 ', 'SSH configuration is usually a text file named '],
    ['SSH 配置通常是一个名为', 'SSH configuration is usually a text file named'],
    ['、没有扩展名的文本文件。终端命令中的 ', ' with no extension. In the terminal command '],
    ['、没有扩展名的文本文件。终端命令中的', 'with no extension. In the terminal command'],
    [' 里，', ', '],
    ['里，', ','],
    [' 就是显存雷达要导入的服务器别名。', ' is the server alias VRAM Radar imports.'],
    ['就是显存雷达要导入的服务器别名。', 'is the server alias VRAM Radar imports.'],
    ['Windows 教程', 'Windows guide'],
    ['PowerShell 是 Windows 自带的命令窗口', 'PowerShell is the command window included with Windows'],
    ['查看步骤', 'View steps'],
    ['先打开 PowerShell', 'Open PowerShell first'],
    ['点击右侧按钮即可打开；也可以按 Windows 键，搜索 ', 'Use the button on the right, or press the Windows key and search for '],
    ['点击右侧按钮即可打开；也可以按 Windows 键，搜索', 'Use the button on the right, or press the Windows key and search for'],
    ['。这里只打开窗口，不会自动执行命令。', '. This opens the window only; it does not run commands automatically.'],
    ['一键打开 PowerShell', 'Open PowerShell'],
    ['让 OpenSSH 告诉你它读取了哪个文件', 'Ask OpenSSH which file it reads'],
    ['点击命令右侧的“复制”，粘贴到刚打开的 PowerShell，再按 Enter。输出中的 ', 'Click Copy, paste the command into PowerShell, and press Enter. The path after '],
    ['点击命令右侧的“复制”，粘贴到刚打开的 PowerShell，再按 Enter。输出中的', 'Click Copy, paste the command into PowerShell, and press Enter. The path after'],
    [' 后面就是配置文件路径。命令不连接服务器；若配置含 ', ' is the configuration file. The command does not connect to a server; if the configuration contains '],
    ['后面就是配置文件路径。命令不连接服务器；若配置含', 'is the configuration file. The command does not connect to a server; if the configuration contains'],
    ['，OpenSSH 仍可能运行其中的本地判断命令。', ', OpenSSH may still run its local condition commands.'],
    ['复制', 'Copy'],
    ['复制PID', 'Copy PID'],
    ['复制 Windows 查找 SSH 配置命令', 'Copy the Windows command for finding SSH configuration'],
    ['查看常用目录', 'Check common folders'],
    ['如果上一步没有显示用户配置，检查 ', 'If the previous step did not show a user configuration, check '],
    ['如果上一步没有显示用户配置，检查', 'If the previous step did not show a user configuration, check'],
    [' 或 ', ' or '],
    ['或', 'or'],
    ['复制 Windows 查看 SSH 目录命令', 'Copy the Windows command for listing the SSH folder'],
    ['还没有 config 文件？创建并打开一个', 'No config file yet? Create and open one'],
    ['下面的命令只会确保 ', 'The following command only makes sure the '],
    ['下面的命令只会确保', 'The following command only makes sure the'],
    [' 目录存在，然后用记事本打开配置文件；已有文件不会被清空。', ' folder exists, then opens the configuration in Notepad. Existing files are not cleared.'],
    ['目录存在，然后用记事本打开配置文件；已有文件不会被清空。', 'folder exists, then opens the configuration in Notepad. Existing files are not cleared.'],
    ['复制 Windows 创建 SSH 配置命令', 'Copy the Windows command for creating SSH configuration'],
    ['macOS 教程', 'macOS guide'],
    ['“终端”是 macOS 自带的命令窗口', 'Terminal is the command window included with macOS'],
    ['先打开“终端”', 'Open Terminal first'],
    ['点击右侧按钮即可打开；也可以按 Command + 空格，搜索“终端”。这里只打开窗口，不会自动执行命令。', 'Use the button on the right, or press Command + Space and search for Terminal. This opens the window only; it does not run commands automatically.'],
    ['一键打开终端', 'Open Terminal'],
    ['点击命令右侧的“复制”，粘贴到刚打开的终端，再按 Return。输出中的 ', 'Click Copy, paste the command into Terminal, and press Return. The path after '],
    ['点击命令右侧的“复制”，粘贴到刚打开的终端，再按 Return。输出中的', 'Click Copy, paste the command into Terminal, and press Return. The path after'],
    ['复制 macOS 查找 SSH 配置命令', 'Copy the macOS command for finding SSH configuration'],
    ['通常是 ', 'Usually '],
    ['通常是', 'Usually'],
    ['；也可能是 ', '; it may also be '],
    ['；也可能是', '; it may also be'],
    ['、Colima 或 OrbStack 的配置。', ', Colima, or OrbStack configuration.'],
    ['复制 macOS 查看 SSH 目录命令', 'Copy the macOS command for listing the SSH folder'],
    ['下面的命令会创建标准目录和文件、设置推荐权限，再用文本编辑器打开。', 'The command creates the standard folder and file, applies recommended permissions, and opens a text editor.'],
    ['复制 macOS 创建 SSH 配置命令', 'Copy the macOS command for creating SSH configuration'],
    ['配置文件应该写什么？查看最小示例', 'What belongs in the file? View a minimal example'],
    ['把示例中的地址和用户名替换为自己的信息。', 'Replace the sample address and username with your own.'],
    [' 是以后在终端和显存雷达中看到的别名。', ' is the alias shown later in the terminal and VRAM Radar.'],
    ['是以后在终端和显存雷达中看到的别名。', 'is the alias shown later in the terminal and VRAM Radar.'],
    ['复制 SSH 配置示例', 'Copy the SSH configuration example'],
    ['使用 VS Code / Cursor Remote-SSH 或其他工具？', 'Using VS Code, Cursor Remote-SSH, or another tool?'],
    ['SSH Config 配置块已复制', 'SSH Config host block copied'],
    ['在 VS Code、Cursor、VSCodium 或 Windsurf 的设置中搜索 ', 'In VS Code, Cursor, VSCodium, or Windsurf settings, search for '],
    ['在 VS Code、Cursor、VSCodium 或 Windsurf 的设置中搜索', 'In VS Code, Cursor, VSCodium, or Windsurf settings, search for'],
    ['。复制显示的完整路径，粘贴到上方“服务器设置文件路径”，再点击“导入并替换列表”。', '. Copy the full path, paste it into Server configuration file above, and click Import and replace list.'],
    ['PuTTY Session 不是 OpenSSH 配置；WSL 中的 ', 'A PuTTY Session is not OpenSSH configuration. '],
    ['PuTTY Session 不是 OpenSSH 配置；WSL 中的', 'A PuTTY Session is not OpenSSH configuration.'],
    [' 也属于 Linux 环境。请先把所需别名转换或复制到当前 Windows/macOS 系统能读取的 OpenSSH config。', ' inside WSL belongs to its Linux environment. Convert or copy the aliases into an OpenSSH config readable by the current Windows or macOS system.'],
    ['也属于 Linux 环境。请先把所需别名转换或复制到当前 Windows/macOS 系统能读取的 OpenSSH config。', 'inside WSL belongs to its Linux environment. Convert or copy the aliases into an OpenSSH config readable by the current Windows or macOS system.'],
    ['找到路径以后', 'After finding the path'],
    ['把完整路径粘贴到上方输入框。', 'Paste the full path into the field above.'],
    ['点击“导入并替换列表”。', 'Click Import and replace list.'],
    ['检查服务器类型和登录方式，最后点击“保存并开始验证”。', 'Review server type and sign-in, then click Save and start validation.'],
    ['已添加的服务器', 'Added servers'],
    ['拖动左侧手柄排序；使用键盘时，聚焦手柄后按上下方向键。连接与登录细节仍放在第二层设置中。', 'Drag the left handle to reorder. For keyboard use, focus the handle and press the arrow keys. Connection and sign-in details remain in the second level.'],
    ['拖动排序；也可按上下方向键', 'Drag to reorder; arrow keys also work'],
    ['拖动服务器排序', 'Drag to reorder server'],
    ['清除搜索后可排序', 'Clear the search to reorder'],
    ['仅一台服务器，无需排序', 'Only one server; no reordering needed'],
    ['手动添加', 'Add manually'],
    ['搜索已添加的服务器', 'Search added servers'],
    ['搜索名称、别名、地址或账号', 'Search name, alias, address, or account'],
    ['稍后设置', 'Set up later'],
    ['取消', 'Cancel'],
    ['上一步', 'Back'],
    ['下一步', 'Next'],
    ['保存并开始验证', 'Save and start validation'],
    ['新服务器', 'New server'],
    ['连接目标与监控类型', 'Connection target and monitoring type'],
    ['测试连接', 'Test connection'],
    ['移除', 'Remove'],
    ['显示名称', 'Display name'],
    ['4090 实验服务器', '4090 lab server'],
    ['连接类型', 'Connection type'],
    ['自动识别（推荐）', 'Auto-detect (recommended)'],
    ['自动识别会在保存验证时实际连接；失败后可手动指定。', 'Auto-detection connects during save validation; choose a type manually if it cannot decide.'],
    ['SSH 直连 / nvidia-smi', 'Direct SSH / nvidia-smi'],
    ['OpenSSH 别名（优先）', 'OpenSSH alias (preferred)'],
    ['主机地址', 'Host address'],
    ['OpenSSH 别名与主机地址填写一个即可。自动导入后通常只需确认连接类型。', 'Enter either an OpenSSH alias or a host address. After auto-import, you usually only need to confirm the connection type.'],
    ['OpenSSH 别名与主机地址填写一个即可。自动导入会沿用 SSH Config，并尽量确认私钥路径和连接类型。', 'Enter either an OpenSSH alias or a host address. Auto-import keeps the SSH config and confirms the key path and connection type when possible.'],
    ['查看已完成任务提醒', 'View completed-task alerts'],
    ['提醒', 'Alert'],
    ['关注', 'Watch'],
    ['已关注', 'Watching'],
    ['登录与高级设置', 'Sign-in and advanced settings'],
    ['Slurm 模块名（可选）', 'Slurm module name (optional)'],
    ['仅填写模块名；程序会安全调用 Environment Modules/Lmod。', 'Enter only the module name; the app invokes Environment Modules/Lmod safely.'],
    ['Slurm bin 目录（可选）', 'Slurm bin directory (optional)'],
    ['填写绝对目录，不需要修改服务器全局环境。', 'Enter an absolute directory; no global server environment changes are required.'],
    ['环境初始化脚本（可选）', 'Environment initialization script (optional)'],
    ['填写远端绝对路径；仅在这台服务器的采集进程中读取。', 'Enter an absolute remote path; it is sourced only by this server collector.'],
    ['Slurm 模块名只能包含字母、数字和 . _ + / @ : -', 'The Slurm module name may contain only letters, numbers, and . _ + / @ : -'],
    ['Slurm 远端路径必须是以 / 开头的绝对路径', 'The remote Slurm path must be absolute and start with /.'],
    ['用户名、端口、密码、私钥和本地标识', 'Username, port, password, private key, and local ID'],
    ['服务器 ID（仅本机）', 'Server ID (local only)'],
    ['用于保存配置和凭据引用，通常不需要修改。', 'Used for local configuration and credential references; it usually does not need to change.'],
    ['端口', 'Port'],
    ['直连主机始终使用；OpenSSH 别名仅在下方勾选后覆盖。', 'Always used for a direct host; for an OpenSSH alias, enable the override below.'],
    ['覆盖 OpenSSH 配置中的端口', 'Override the port in OpenSSH configuration'],
    ['用户名', 'Username'],
    ['私钥路径（可选）', 'Private key path (optional)'],
    ['选择或粘贴私钥路径', 'Select or paste a private key path'],
    ['OpenSSH 配置文件（可选）', 'OpenSSH configuration file (optional)'],
    ['自动导入会填写来源；切换直连或文件移动后可在这里清除或修改。', 'Auto-import fills in the source. Clear or update it here after switching to direct connection or moving the file.'],
    ['登录密码（可选）', 'Login password (optional)'],
    ['留空则保持已有密码', 'Leave blank to keep the saved password'],
    ['未保存密码', 'No saved password'],
    ['默认使用 OpenSSH、ssh-agent 或私钥', 'Uses OpenSSH, ssh-agent, or a private key by default'],
    ['删除已保存的登录密码', 'Delete saved login password'],
    ['显示其他用户的任务与命令摘要', 'Show job and command summaries for other users'],
    ['SSH 直连：显示其他用户的 GPU 进程与经本地遮盖、限长的命令摘要。', 'Direct SSH: show other users\' GPU processes with locally redacted, length-limited command summaries.'],
    ['Slurm：显示其他用户的作业名、状态与时间；调度器视图不读取完整 shell 命令。', 'Slurm: show other users\' job names, states, and times; the scheduler view does not read full shell commands.'],
    ['未配置免密引导时，已保存的密码用于认证；完成 SSH Key 引导后会优先使用私钥，密码只在密钥被拒绝时本地回退。首次连接前，请先在 OpenSSH 中核对并接受正确的主机密钥。', 'Before SSH Key setup, a saved password is used for authentication. After setup, the private key is preferred and the password is only a local fallback if the key is rejected. Before the first connection, verify and accept the correct host key in OpenSSH.'],
    ['一键配置 SSH 免密登录', 'Set up passwordless SSH'],
    ['安全生成或复用密钥，部署后自动验证', 'Safely generate or reuse a key and verify it after deployment'],
    ['复用现有密钥，部署后自动验证', 'Reuse an existing key and verify it after deployment'],
    ['开始', 'Start'],
    [' 是更方便的服务器登录方式。配置完成后，后续连接通常不需要重复输入密码。', ' provides convenient, secure server sign-in. After setup, later connections usually do not require a password.'],
    ['是更方便的服务器登录方式。配置完成后，后续连接通常不需要重复输入密码。', 'provides convenient, secure server sign-in. After setup, later connections usually do not require a password.'],
    ['私钥始终留在本机；只把公钥写入当前账号的 ', 'The private key always stays on this computer. Only the public key is written to the current account\'s '],
    ['私钥始终留在本机；只把公钥写入当前账号的', 'The private key always stays on this computer. Only the public key is written to the current account\'s'],
    ['远端只做非替换式追加；会检查重复项、文件类型、所有者和权限。', 'The remote file is append-only. Duplicates, file type, owner, and permissions are checked.'],
    ['追加后若验证或本地保存失败，不会自动改写 ', 'If verification or local saving fails after appending, the app will not automatically rewrite '],
    ['追加后若验证或本地保存失败，不会自动改写', 'If verification or local saving fails after appending, the app will not automatically rewrite'],
    ['；会保留匹配密钥并提示重试或精确手动移除。', '. The matching key is retained with instructions to retry or remove that exact key manually.'],
    ['SSH Key 来源', 'SSH Key source'],
    ['使用现有密钥', 'Use an existing key'],
    ['推荐；不会修改本地密钥', 'Recommended; local keys are not modified'],
    ['生成专用密钥', 'Generate a dedicated key'],
    ['不覆盖现有密钥，保存在本机应用配置目录', 'Does not overwrite existing keys; stored in the local app configuration folder'],
    ['现有私钥路径', 'Existing private key path'],
    ['对应公钥路径（可选）', 'Matching public key path (optional)'],
    ['私钥带口令时建议选择 .pub，并先加载 ssh-agent。', 'For a passphrase-protected private key, select the .pub file and load ssh-agent first.'],
    ['生成专用密钥时会发生什么？', 'What happens when a dedicated key is generated?'],
    ['系统生成独立的 Ed25519 密钥，不覆盖 ', 'The app generates a separate Ed25519 key without overwriting files in '],
    ['系统生成独立的 Ed25519 密钥，不覆盖', 'The app generates a separate Ed25519 key without overwriting files in'],
    [' 中任何现有文件。为了后台自动连接，专用私钥不设置密钥口令，并依靠当前系统用户的文件权限保护；需要口令保护时请选择现有密钥并使用 ssh-agent。', '. To support background connections, the dedicated private key has no passphrase and is protected by current-user file permissions. To use a passphrase, choose an existing key and ssh-agent.'],
    ['中任何现有文件。为了后台自动连接，专用私钥不设置密钥口令，并依靠当前系统用户的文件权限保护；需要口令保护时请选择现有密钥并使用 ssh-agent。', 'To support background connections, the dedicated private key has no passphrase and is protected by current-user file permissions. To use a passphrase, choose an existing key and ssh-agent.'],
    ['配置并验证', 'Configure and verify'],
    ['请先保存地址和用户名；如当前密钥不能登录，再保存一次服务器密码。', 'Save the address and username first. If the current key cannot sign in, save the server password once.'],
    ['开始设置', 'Start setup'],
    ['登录账号', 'Login account'],
    ['主目录', 'Home folder'],
    ['主机 CPU', 'Host CPU'],
    ['个逻辑核心', 'logical cores'],
    ['逻辑核心未知', 'Logical cores unavailable'],
    ['主机内存', 'Host memory'],
    ['置顶', 'Pin'],
    ['取消置顶', 'Unpin'],
    ['置顶这台服务器', 'Pin this server'],
    ['取消置顶这台服务器', 'Unpin this server'],
    ['无法更新置顶', 'Unable to update pin'],
    ['负载', 'load'],
    ['使用率：主机近期整体 CPU 忙碌占比（不是单进程）。', 'Usage %: recent host-wide CPU busy share (not per-process).'],
    ['负载 1/5/15：可运行或不可中断等待任务平均数——与逻辑核对比（持续高于逻辑核≈偏满）。', 'Load 1/5/15: average runnable or uninterruptible tasks — compare to logical cores (sustained load above cores ≈ saturation).'],
    ['内存：主机内存；内核提供时优先使用 MemAvailable。', 'Memory: host RAM; prefers MemAvailable when the kernel exposes it.'],

    ['运行 / 等待任务数', 'Running / waiting tasks'],
    ['1、5、15 分钟数值表示正在运行、等待 CPU 或处于不可中断 I/O 等待中的平均任务数。', 'The 1, 5, and 15 minute values are the average number of tasks running, waiting for CPU, or waiting in uninterruptible I/O.'],
    ['使用率是主机近期整体 CPU 忙碌占比。1、5、15 分钟数值表示正在运行、等待 CPU 或处于不可中断 I/O 等待中的平均任务数。主机内存优先使用内核提供的 MemAvailable。', 'Usage is the recent host-wide CPU busy share. The 1, 5, and 15 minute values are the average number of tasks running, waiting for CPU, or waiting in uninterruptible I/O. Host memory uses MemAvailable when the kernel exposes it.'],
    ['进程 CPU', 'Process CPU'],
    ['1 分钟', '1 min'],
    ['5 分钟', '5 min'],
    ['15 分钟', '15 min'],
    ['系统负载（1/5/15 分钟）', 'Load average (1/5/15 min)'],
    ['暂停', 'Pause'],
    ['数据已过期', 'Data is stale'],
    ['网络不可达', 'Network unreachable'],
    ['尚未取得服务器数据', 'No server data yet'],
    ['这台服务器已暂停监控', 'Monitoring is paused for this server'],
    ['服务器连接超时', 'Server connection timed out'],
    ['错误代码：', 'Error code:'],
    ['当前没有可显示的 GPU 快照。', 'No GPU snapshot is available.'],
    ['旧快照仅供参考，不计入顶部实时汇总。', 'The old snapshot is for reference only and is excluded from the live summary.'],
    ['即将自动重试', 'Retrying automatically soon'],
    ['GPU 实时显存', 'Live GPU memory'],
    ['卡型', 'GPU model'],
    ['已用显存', 'Used VRAM'],
    ['空闲显存', 'Free VRAM'],
    ['利用率', 'Utilization'],
    ['温度', 'Temperature'],
    ['GPU 进程', 'GPU processes'],
    ['当前 GPU 进程', 'Current GPU processes'],
    ['当前 GPU 进程，可横向滚动', 'Current GPU processes; scroll horizontally'],
    ['进程 / 任务', 'Process / job'],
    ['GPU 明细', 'GPU details'],
    ['显存合计', 'Total VRAM'],
    ['启动时间', 'Started'],
    ['查看命令摘要', 'View command summary'],
    ['敏感参数已遮盖', 'Sensitive arguments redacted'],
    ['敏感参数已遮盖 · 已安全截断', 'Sensitive arguments redacted · safely truncated'],
    ['已安全截断', 'Safely truncated'],
    ['其他用户命令摘要未启用', 'Other-user command summaries are disabled'],
    ['命令详情受服务器权限限制', 'Command details are restricted by server permissions'],
    ['GPU 未识别', 'GPU not identified'],
    ['显存未知', 'VRAM unknown'],
    ['权限受限', 'Permission limited'],
    ['计时待确认', 'Timing unverified'],
    ['运行时长不可用', 'Runtime unavailable'],
    ['已观测运行至少', 'Observed running for at least'],
    ['查看完整任务名称：', 'View full job name:'],
    ['我的进程', 'My processes'],
    ['当前没有我的 GPU 进程', 'I have no active GPU processes'],
    ['其他用户', 'Other users'],
    ['当前没有可见的其他用户 GPU 进程', 'No other user GPU processes are visible'],
    ['说明', 'About'],
    ['显示当前直连服务器可见的 GPU 进程；不是调度队列，不包含排队或完成历史。可见命令只显示经过敏感参数遮盖与长度限制的摘要，其他用户摘要还需在服务器设置中开启。', 'Shows GPU processes visible on the current direct server. This is not a scheduler queue and does not include pending or completed history. Visible commands are redacted and length-limited; summaries for other users must also be enabled in server settings.'],
    ['代码工作目录', 'Code workspace'],
    ['自动定位', 'Auto-detected'],
    ['已复用缓存', 'Cached'],
    ['刷新目录', 'Refresh folder'],
    ['固定当前目录', 'Pin current folder'],
    ['展开已加载', 'Expand loaded folders'],
    ['固定为默认目录', 'Pin as default folder'],
    ['当前文件夹为空', 'This folder is empty'],
    ['展开后读取', 'Load when expanded'],
    ['展开时读取文件夹名称、类型、大小和修改时间', 'Load names, types, sizes, and modification times when expanded'],
    ['登录账号和主目录', 'Login account and home folder'],
    ['收藏服务器', 'Favorite server'],
    ['暂停监控这台服务器', 'Pause monitoring for this server'],
    ['GPU 实时显存，可横向滚动', 'Live GPU memory; scroll horizontally'],
    ['显存占用率', 'VRAM usage'],
    ['复制工作目录路径', 'Copy workspace path'],
    ['代码工作目录结构', 'Code workspace structure'],
    ['复制文件夹路径', 'Copy folder path'],
    ['拖动到左侧', 'Drag to the left'],
    ['Slurm GPU 调度状态 · 刚刚更新', 'Slurm GPU scheduler · updated just now'],
    ['GPU 节点容量', 'GPU node capacity'],
    ['GPU 节点容量，可横向滚动', 'GPU node capacity; scroll horizontally'],
    ['节点', 'Nodes'],
    ['分区', 'Partition'],
    ['卡型 / 单卡显存', 'GPU model / VRAM per GPU'],
    ['空闲 GPU', 'Free GPUs'],
    ['空闲容量未知', 'Free capacity unknown'],
    ['节点分配明细不可读', 'Node allocation details unavailable'],
    ['当前账号无法读取 Slurm 全局节点分配明细。节点和可见任务仍会显示；为避免把其他用户占用误报为空闲，空闲容量按未知处理。', 'This account cannot read cluster-wide Slurm node allocation details. Nodes and visible jobs are still shown; free capacity is treated as unknown to avoid reporting GPUs used by other users as idle.'],
    ['当前 Slurm 不支持完整任务字段，已使用兼容查询；运行中节点任务仍会显示，尚未分配节点的 GPU 排队任务可能不可识别。', 'This Slurm version does not support the complete job fields, so a compatibility query is in use. Jobs on running nodes remain visible; queued GPU jobs without assigned nodes may not be identified.'],
    ['当前账号不能读取全局 Slurm 队列，已自动回退为当前账号任务；GPU 节点仍会继续显示。', 'This account cannot read the global Slurm queue, so the app automatically fell back to this account’s jobs; GPU nodes remain visible.'],
    ['调度显存占用', 'Scheduled VRAM allocation'],
    ['活动任务', 'Active jobs'],
    ['节点状态', 'Node state'],
    ['按 Slurm 已分配整卡计算，不代表进程实时显存', 'Calculated from whole GPUs allocated by Slurm; not live process VRAM'],
    ['已分配', 'Allocated'],
    ['即将完成', 'Completing'],
    ['不可用', 'Unavailable'],
    ['排空中', 'Draining'],
    ['正在排空', 'Draining'],
    ['故障', 'Failed'],
    ['部分占用', 'Partially allocated'],
    ['已保留', 'Reserved'],
    ['维护中', 'Maintenance'],
    ['排队', 'Pending'],
    ['运行', 'Running'],
    ['完成', 'Completed'],
    ['我的任务', 'My jobs'],
    ['正在运行与排队', 'Running and pending'],
    ['当前 GPU 任务队列', 'Current GPU job queue'],
    ['用户', 'User'],
    ['任务 ID', 'Job ID'],
    ['任务名称', 'Job name'],
    ['状态', 'State'],
    ['节点或排队原因', 'Node or pending reason'],
    ['运行时长', 'Elapsed'],
    ['提交时间', 'Submitted'],
    ['时间限额', 'Time limit'],
    ['占用 GPU', 'GPUs'],
    ['我', 'Me'],
    ['运行中', 'Running'],
    ['过去 24 小时结果', 'Results from the last 24 hours'],
    ['近 24 小时 GPU 任务结果', 'GPU job results from the last 24 hours'],
    ['结束时间', 'Ended'],
    ['已完成', 'Completed'],
    ['排队中', 'Pending'],
    ['等待 GPU 资源', 'Waiting for GPU resources'],
    ['尚未开始', 'Not started'],
    ['过去 24 小时内当前账号未看到其他用户的 GPU 终态任务', 'No completed GPU jobs from other users were visible to this account in the last 24 hours'],
    ['仅显示 Slurm 对当前登录账号可见的 GPU 作业；集群权限策略可能隐藏其他用户任务。任务名称来自提交者设置的 Slurm JobName；这里不是计算节点内的 PID 进程列表。', 'Shows GPU jobs visible to the current account through Slurm. Cluster policy may hide other users\' jobs. Job names are Slurm JobName values; this is not a PID process list from compute nodes.'],
    ['集群容量', 'Cluster capacity'],
    ['大集群模式', 'Large-cluster mode'],
    ['节点明细', 'Node details'],
    ['按需读取', 'Load on demand'],
    ['搜索节点', 'Search nodes'],
    ['节点名', 'Node name'],
    ['全部卡型', 'All GPU models'],
    ['全部分区', 'All partitions'],
    ['仅空闲', 'Available only'],
    ['仅异常', 'Issues only'],
    ['筛选', 'Filter'],
    ['展开后按页读取节点', 'Expand to load nodes page by page'],
    ['暂无 GPU 任务', 'No GPU jobs'],
    ['当前没有我的排队或运行中 GPU 任务', 'I have no pending or running GPU jobs'],
    ['当前服务器未提供近期任务历史，仍可查看当前任务。', 'This server does not provide recent job history; current jobs remain available.'],
    ['当前账号未看到其他用户的活动 GPU 任务', 'No active GPU jobs from other users are visible to this account'],
    ['正在配置中', 'Configuring'],
    ['正在配置并验证服务器', 'Configuring and validating server'],
    ['正在连接 SSH、检查Slurm 调度器并读取第一份 GPU 数据；完成前不会显示为错误。', 'Connecting through SSH, checking the Slurm scheduler, and reading the first GPU snapshot. This is not shown as an error while setup is in progress.'],
    ['正在连接 SSH、检查GPU 采集器并读取第一份 GPU 数据；完成前不会显示为错误。', 'Connecting through SSH, checking the GPU collector, and reading the first GPU snapshot. This is not shown as an error while setup is in progress.'],
    ['Slurm GPU 调度状态 · 正在建立首次有效快照', 'Slurm GPU scheduler · creating the first valid snapshot'],
    ['GPU 实时显存 · 正在建立首次有效快照', 'Live GPU memory · creating the first valid snapshot'],
    ['需要认证', 'Authentication required'],
    ['重新验证', 'Validate again'],
    ['连接设置', 'Connection settings'],
    ['上次 GPU 进程', 'Last GPU processes'],
    ['这是上次成功采样时可见的 GPU 进程，不能据此判断它们现在仍在运行。', 'These GPU processes were visible in the last successful sample; this does not mean they are still running.'],
    ['复制节点名', 'Copy node name'],
    ['GPU 调度占用率', 'Scheduled GPU allocation'],
    ['GPU 任务列表，可横向滚动', 'GPU job list; scroll horizontally'],
    ['复制任务 ID', 'Copy job ID'],
    ['显存雷达：资源可用', 'VRAM Radar: resources available'],
    ['你设置的 GPU 条件已有匹配结果。', 'Your GPU requirements now have a matching result.'],
    ['未能检查更新', 'Could not check for updates'],
    ['重试', 'Retry'],
    ['安装并重启', 'Install and restart'],
    ['下载并显示', 'Download and show'],
    ['打开 Release', 'Open Release'],
    ['更新包已通过 GitHub 元数据校验，确认后会安全替换并自动重启。', 'The package passed GitHub metadata validation. After confirmation, it will be replaced safely and the app will restart.'],
    ['更新包会先校验 SHA-256，再在 Finder 中显示。', 'The package will be SHA-256 verified before it is shown in Finder.'],
    ['当前版本需要从 GitHub Release 手动安装。', 'Install this version manually from the GitHub Release.'],
    ['GitHub 暂时限制了匿名检查，请稍后重试', 'GitHub temporarily limited anonymous update checks. Try again later.'],
    ['无法验证 GitHub 的 HTTPS 证书', 'Could not verify the GitHub HTTPS certificate.'],
    ['无法解析 GitHub 地址，请检查 DNS 或网络', 'Could not resolve GitHub. Check DNS or network access.'],
    ['连接 GitHub 超时，请稍后重试', 'The GitHub connection timed out. Try again later.'],
    ['应用缺少 macOS 系统证书信任组件', 'The app is missing macOS system trust support.'],
    ['GitHub 返回了无法解析的响应', 'GitHub returned a response that could not be parsed.'],
    ['GitHub Release 元数据不完整或不受信任', 'GitHub Release metadata is incomplete or untrusted.'],
    ['暂时无法连接 GitHub，请稍后重试', 'Could not connect to GitHub. Try again later.'],
  ]);

  const PATTERNS = [
    [/^(服务器|Slurm)\s*返回了(不兼容的|不安全的|不完整的|无效的|无法识别的|矛盾的|过多的|重复的)(.+)$/, (_, source, issue, field) => `${source === '服务器' ? 'Server' : source} returned ${{'不兼容的': 'incompatible', '不安全的': 'unsafe', '不完整的': 'incomplete', '无效的': 'invalid', '无法识别的': 'unrecognized', '矛盾的': 'inconsistent', '过多的': 'too many', '重复的': 'duplicate'}[issue]} ${translated(field)}`],
    [/^SSH 身份验证失败，请检查(.+)$/, (_, detail) => `SSH authentication failed; check ${translated(detail)}`],
    [/^已解析 ([\d,.]+) 台服务器候选(.*)$/, (_, count, suffix) => `Parsed ${count} server candidates${translated(suffix)}`],
    [/^已发现 ([\d,.]+) 个服务器设置来源$/, 'Found $1 server configuration sources'],
    [/^最多可单独关注 ([\d,.]+) 个任务$/, 'You can individually watch up to $1 tasks'],
    [/^([\d,.]+)天$/, '$1d'],
    [/^([\d,.]+)秒$/, '$1s'],
    [/^([\d,.]+)天([\d,.]+)分钟$/, '$1d $2m'],
    [/^界面缩放 ([\d,.]+)%$/, 'Interface zoom $1%'],
    [/^删除视图 (.+)$/, 'Delete view $1'],
    [/^复制(.+)$/, (_, label) => `Copy ${translated(label)}`],
    [/^(.+)，可横向滚动$/, (_, label) => `${translated(label)}; scroll horizontally`],
    [/^错误代码：(.+?) · 最后成功：(.+?)(。.*)$/, (_, code, last, suffix) => `Error code: ${code} · Last success: ${translated(last)}${translated(suffix)}`],
    [/^将为“([\s\S]+)”生成一把独立的 Ed25519 密钥。[\s\S]+是否继续？$/, (_, name) => `Generate a dedicated Ed25519 key for “${name}”?\n\nThe private key stays on this computer without replacing existing keys. The public key is appended without replacing authorized_keys. If verification or local saving fails, both keys are retained to protect concurrent changes; retry or remove the exact key manually.`],
    [/^将为“([\s\S]+)”部署所选密钥的公钥。[\s\S]+是否继续？$/, (_, name) => `Install the selected public key for “${name}”?\n\nThe private key is not uploaded. The public key is appended only if absent, without replacing authorized_keys. If verification or local saving fails, remote files are not rewritten automatically; retry or remove the exact key manually.`],
    [/^当前：(.+) · (.+)$/, (_, name, section) => `Current: ${name} · ${translated(section)}`],
    [/^当前：(.+)$/, 'Current: $1'],
    [/^状态更新于 (.+) · 每 ([\d,.]+) 秒$/, 'Updated $1 · every $2 seconds'],
    [/^发现 VRAM Radar (.+) 的修复构建$/, 'VRAM Radar $1 repair build available'],
    [/^发现 VRAM Radar (.+)$/, 'VRAM Radar $1 available'],
    [/^当前版本 (.+)。更新包已通过 GitHub 元数据校验，确认后会安全替换并自动重启。$/, 'Current version $1. The package passed GitHub metadata validation and will be replaced safely before restart.'],
    [/^当前版本 (.+)。更新包会先校验 SHA-256，再在 Finder 中显示。$/, 'Current version $1. The package will be SHA-256 verified before it is shown in Finder.'],
    [/^当前版本 (.+)。当前版本需要从 GitHub Release 手动安装。$/, 'Current version $1. Install the update manually from the GitHub Release.'],
    [/^约 ([\d,.]+) 秒后自动重试$/, 'Retrying automatically in about $1 seconds'],
    [/^第 ([\d,.]+) 台服务器：(.+)$/, 'Server $1: $2'],
    [/^已解析 ([\d,.]+) 台服务器候选(.+)$/, 'Parsed $1 server candidates$2'],
    [/^总量 ([\d,.]+) GiB$/, '$1 GiB total'],
    [/^([\d,.]+)\/([\d,.]+) 台监控就绪[\s·・]+([\d,.]+) 块 GPU$/, '$1/$2 servers ready · $3 GPUs'],
    [/^GPU 实时显存 · 刚刚更新$/, 'Live GPU memory · updated just now'],
    [/^([\d,.]+) 个逻辑核心$/, '$1 logical cores'],
    [/^([\d,.]+) 个可见进程$/, '$1 visible processes'],
    [/^([\d,.]+) 个$/, '$1'],
    [/^([\d,.]+) 位$/, '$1 users'],
    [/^([\d,.]+) 项$/, '$1 items'],
    [/^([\d,.]+)–([\d,.]+) \/ ([\d,.]+) 台$/, '$1–$2 / $3 servers'],
    [/^([\d,.]+) 台$/, '$1 servers'],
    [/^([\d,.]+) GPU · ([\d,.]+) GiB 可用$/, '$1 GPU · $2 GiB free'],
    [/^在线显存池，可用 ([\d,.]+) GiB，共 ([\d,.]+) GiB，可用率 ([\d,.]+)%，状态充足$/, 'Online VRAM pool: $1 GiB free of $2 GiB ($3%), healthy'],
    [/^修改时间：(.+)$/, 'Modified: $1'],
    [/^查看完整任务名称：(.+)$/, 'View full job name: $1'],
    [/^(.+)，监控就绪，([\d,.]+) GPU · ([\d,.]+) GiB 可用$/, '$1, monitoring ready, $2 GPU · $3 GiB free'],
    [/^收藏 (.+)$/, 'Favorite $1'],
    [/^收藏这张 GPU (.+)$/, 'Favorite GPU $1'],
    [/^取消收藏这张 GPU (.+)$/, 'Unfavorite GPU $1'],
    [/^当前为筛选结果第 ([\d,.]+) 台，共 ([\d,.]+) 台$/, 'Filtered server $1 of $2'],
    [/^拖动第 ([\d,.]+) 台服务器排序；按上下方向键微调$/, 'Drag server $1 to reorder; use the arrow keys for precise movement'],
    [/^(.+) 已移动到第 ([\d,.]+) 位$/, '$1 moved to position $2'],
    [/^(.+) · ([\d,.]+) GiB\/卡$/, '$1 · $2 GiB/GPU'],
    [/^([\d,.]+) 张（共 ([\d,.]+) 张）$/, '$1 free of $2 GPUs'],
    [/^已分配 ([\d,.]+) GiB$/, '$1 GiB allocated'],
    [/^调度器未分配 ([\d,.]+) \/ ([\d,.]+) GiB$/, '$1 / $2 GiB unallocated by scheduler'],
    [/^([\d,.]+) 当前 · ([\d,.]+) 近期$/, '$1 current · $2 recent'],
    [/^([\d,.]+) 条$/, '$1 jobs'],
    [/^([\d,.]+)天([\d,.]+)小时$/, '$1d $2h'],
    [/^([\d,.]+)小时([\d,.]+)分钟$/, '$1h $2m'],
    [/^([\d,.]+)小时$/, '$1h'],
    [/^([\d,.]+)分钟$/, '$1m'],
    [/^([\d,.]+) 张$/, '$1 GPUs'],
    [/^([\d,.]+) 个节点 · 先按卡型和分区汇总$/, '$1 nodes · summarized by GPU model and partition'],
    [/^每页最多 ([\d,.]+) 个节点$/, 'Up to $1 nodes per page'],
    [/^GPU 实时显存 · 最后成功：从未成功$/, 'Live GPU memory · no successful sample yet'],
    [/^GPU 实时显存 · 最后成功：\s*(.+)$/, 'Live GPU memory · last success: $1'],
    [/^Slurm GPU 调度状态 · 最后成功：\s*(.+)$/, 'Slurm GPU scheduler · last success: $1'],
    [/^错误代码：\s*(.+?) · 最后成功：(.+?) · 约 ([\d,.]+) 秒后自动重试。旧快照仅供参考，不计入顶部实时汇总。$/, 'Error code: $1 · Last success: $2 · Retrying automatically in about $3 seconds. The old snapshot is for reference only and is excluded from the live summary.'],
    [/^错误代码：\s*(.+?) · 最后成功：(.+?) · 即将自动重试。旧快照仅供参考，不计入顶部实时汇总。$/, 'Error code: $1 · Last success: $2 · Retrying automatically soon. The old snapshot is for reference only and is excluded from the live summary.'],
    [/^错误代码：\s*(.+?) · 最后成功：(.+?)。旧快照仅供参考，不计入顶部实时汇总。$/, 'Error code: $1 · Last success: $2. The old snapshot is for reference only and is excluded from the live summary.'],
    [/^错误代码：\s*(.+?) · 约 ([\d,.]+) 秒后自动重试。当前没有可显示的 GPU 快照。$/, 'Error code: $1 · Retrying automatically in about $2 seconds. No GPU snapshot is available.'],
    [/^错误代码：(.+)。当前没有可显示的 GPU 快照。$/, 'Error code: $1. No GPU snapshot is available.'],
    [/^([\d,.]+) 运行$/, '$1 running'],
    [/^(.+)，监控就绪，([\d,.]+) GPU · ([\d,.]+) GiB 可用，([\d,.]+) 运行$/, '$1, monitoring ready, $2 GPU · $3 GiB free, $4 running'],
    [/^(.+)，需要认证，需要认证$/, '$1, authentication required'],
    [/^([\d,.]+) 天$/, '$1 days'],
    [/^([\d,.]+) 小时$/, '$1 hours'],
    [/^([\d,.]+) 分钟$/, '$1 minutes'],
    [/^([\d,.]+) 秒$/, '$1 seconds'],
    [/^([\d,.]+)核$/, '$1c'],
    [/^([\d,.]+)物理\/([\d,.]+)逻辑$/, '$1p/$2c'],
    [/^核心：逻辑 ([\d,.]+)（逻辑含超线程）。$/, 'Cores: logical $1 (SMT/HT included when present).'],
    [/^核心：逻辑 ([\d,.]+)（物理 ([\d,.]+)；逻辑含超线程）。$/, 'Cores: logical $1 (physical $2; SMT/HT included in logical).'],
    [/^时钟：当前约 ([\d,.]+) MHz。$/, 'Clock ~$1 MHz.'],
    [/^([\d,.]+)--([\d,.]+) \/ ([\d,.]+) 台$/, '$1--$2 / $3 servers'],
    [/^([\d,.]+)[\u2013-]{1,2}([\d,.]+) \/ ([\d,.]+) 台$/, '$1--$2 / $3 servers'],
    [/^([\d,.]+)\/([\d,.]+) 台监控就绪[\s·・]+([\d,.]+) 块 GPU$/, '$1/$2 servers ready · $3 GPUs'],
    [/^状态更新于 (.+?) [·・] 每 ([\d,.]+) 秒$/, 'Status updated at $1 · every $2 s'],
  ];
  const ATTRIBUTES = ['aria-label', 'title', 'placeholder', 'alt', 'data-label'];
  const textRecords = new WeakMap();
  const attributeRecords = new WeakMap();
  let language = 'zh-CN';
  let observer = null;

  function translated(source) {
    const value = String(source ?? '');
    if (language !== 'en' || !/[\u3400-\u9fff]/u.test(value)) return value;
    const leading = value.match(/^\s*/u)?.[0] || '';
    const trailing = value.match(/\s*$/u)?.[0] || '';
    const core = value.slice(leading.length, value.length - trailing.length);
    if (ENGLISH.has(core)) return `${leading}${ENGLISH.get(core)}${trailing}`;
    for (const [pattern, replacement] of PATTERNS) {
      if (pattern.test(core)) {
        const rendered = typeof replacement === 'function'
          ? core.replace(pattern, replacement)
          : core.replace(pattern, (...groups) => replacement.replace(/[$]([0-9]+)/g,
              (_, index) => translated(groups[Number(index)])));
        return `${leading}${rendered}${trailing}`;
      }
    }
    // Translate independently composed UI sentences without altering unknown
    // server names, paths, or commands. Each recursive part is strictly shorter.
    const parts = core.split(/(\n+| · |；|。)/u);
    if (parts.length > 1) {
      const rendered = parts.map(part => ['；', '。'].includes(part) ? part : translated(part));
      if (rendered.some((part, index) => part !== parts[index])) {
        return leading + rendered.map(part => part === '；' ? '; ' : part === '。' ? '. ' : part).join('') + trailing;
      }
    }
    return value;
  }

  function updateText(node) {
    if (!node?.parentElement || ['SCRIPT', 'STYLE'].includes(node.parentElement.tagName)) return;
    const current = node.nodeValue || '';
    let record = textRecords.get(node);
    if (record && current === record.rendered && record.language === language) return;
    if (!record || current !== record.rendered) record = {source: current, rendered: current, language};
    record.rendered = language === 'en' ? translated(record.source) : record.source;
    record.language = language;
    textRecords.set(node, record);
    if (current !== record.rendered) node.nodeValue = record.rendered;
  }

  function updateAttribute(element, name) {
    if (!element?.hasAttribute?.(name)) return;
    const current = element.getAttribute(name) || '';
    let records = attributeRecords.get(element);
    if (!records) {
      records = new Map();
      attributeRecords.set(element, records);
    }
    let record = records.get(name);
    if (record && current === record.rendered && record.language === language) return;
    if (!record || current !== record.rendered) record = {source: current, rendered: current, language};
    record.rendered = language === 'en' ? translated(record.source) : record.source;
    record.language = language;
    records.set(name, record);
    if (current !== record.rendered) element.setAttribute(name, record.rendered);
  }

  function localizeTree(root) {
    if (!root) return;
    if (root.nodeType === Node.TEXT_NODE) updateText(root);
    if (root.nodeType === Node.ELEMENT_NODE) ATTRIBUTES.forEach(name => updateAttribute(root, name));
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT);
    let node = walker.nextNode();
    while (node) {
      if (node.nodeType === Node.TEXT_NODE) updateText(node);
      else ATTRIBUTES.forEach(name => updateAttribute(node, name));
      node = walker.nextNode();
    }
  }

  function setLanguage(nextLanguage) {
    language = nextLanguage === 'en' ? 'en' : 'zh-CN';
    document.documentElement.lang = language;
    localizeTree(document.documentElement);
    document.dispatchEvent(new CustomEvent('vram-radar-language-changed', {detail: {language}}));
    return language;
  }

  const api = {
    get language() { return language; },
    setLanguage,
    translateText(source, targetLanguage = 'en') {
      const previous = language;
      language = targetLanguage === 'en' ? 'en' : 'zh-CN';
      const result = translated(source);
      language = previous;
      return result;
    },
  };

  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  if (typeof window === 'undefined' || typeof document === 'undefined') return;
  window.VRAMRadarI18n = api;
  document.addEventListener('DOMContentLoaded', () => {
    localizeTree(document.documentElement);
    observer = new MutationObserver(mutations => {
      for (const mutation of mutations) {
        if (mutation.type === 'characterData') updateText(mutation.target);
        else if (mutation.type === 'attributes') updateAttribute(mutation.target, mutation.attributeName);
        else mutation.addedNodes.forEach(localizeTree);
      }
    });
    observer.observe(document.documentElement, {
      subtree: true,
      childList: true,
      characterData: true,
      attributes: true,
      attributeFilter: ATTRIBUTES,
    });
  }, {once: true});
})();
