(() => {
  'use strict';

  const ENGLISH = new Map([
    ['显存雷达', 'VRAM Radar'],
    ['欢迎使用显存雷达', 'Welcome to VRAM Radar'],
    ['先添加一台 GPU 服务器', 'Add your first GPU server'],
    ['自动查找本机 SSH 配置，确认连接方式后开始监控。', 'Discover local SSH configuration, confirm the connection, and start monitoring.'],
    ['首次配置说明', 'First-time setup'],
    ['自动发现', 'Auto-discover'],
    ['检查登录方式', 'Review sign-in'],
    ['保存并开始监控', 'Save and monitor'],
    ['开始配置', 'Start setup'],
    ['没有 SSH 配置也没关系，向导内有 Windows 和 macOS 的完整教程。', 'No SSH configuration yet? The guide includes complete Windows and macOS instructions.'],
    ['GPU 资源总览', 'GPU overview'],
    ['当前可用显存', 'Currently available VRAM'],
    ['所有监控就绪 GPU 合计', 'Across all monitored GPUs'],
    ['可用比例', 'Available capacity'],
    ['监控就绪', 'Monitoring ready'],
    ['SSH 已认证 / 资源已读取', 'SSH authenticated / resources loaded'],
    ['已读取 GPU', 'GPUs loaded'],
    ['块', ' GPUs'],
    ['仅统计当前有效快照', 'Current valid snapshots only'],
    ['可用显存、卡型与任务状态', 'Available VRAM, GPU models, and jobs'],
    ['GPU 概览', 'GPU overview'],
    ['帮我找一台可用 GPU', 'Find available GPUs'],
    ['按卡数、单卡空闲显存、卡型与分区筛选', 'Filter by GPU count, free VRAM per GPU, model, and partition'],
    ['填写需求', 'Set requirements'],
    ['收起', 'Collapse'],
    ['已保存的资源筛选', 'Saved resource filters'],
    ['GPU 数量', 'GPU count'],
    ['单卡最低空闲显存', 'Minimum free VRAM per GPU'],
    ['卡型（可选）', 'GPU model (optional)'],
    ['例如 4090、A100', 'e.g. 4090 or A100'],
    ['更多条件', 'More filters'],
    ['分区、同节点与结果数量', 'Partition, same-node placement, and result count'],
    ['展开', 'Expand'],
    ['编辑', 'Edit'],
    ['分区（可选）', 'Partition (optional)'],
    ['例如 gpu-large', 'e.g. gpu-large'],
    ['显示结果', 'Results'],
    ['前 3 个', 'Top 3'],
    ['前 5 个', 'Top 5'],
    ['前 10 个', 'Top 10'],
    ['多张 GPU 必须在同一节点', 'Place multiple GPUs on one node'],
    ['查找可用资源', 'Find resources'],
    ['本次运行有资源时提醒我', 'Notify me when this app finds a match'],
    ['保存这组条件', 'Save these filters'],
    ['下次一键恢复', 'Reuse them next time'],
    ['保存', 'Save'],
    ['例如 8×H100', 'e.g. 8×H100'],
    ['保存视图', 'Save view'],
    ['服务器状态', 'Server status'],
    ['展开查看 GPU、进程和任务', 'Expand to inspect GPUs, processes, and jobs'],
    ['正在读取', 'Loading'],
    ['服务器内容显示方式', 'Server content display'],
    ['一键收起', 'Collapse all'],
    ['上一页', 'Previous'],
    ['下一页', 'Next'],
    ['服务器快速导航', 'Quick server navigation'],
    ['服务器目录在右侧，拖动或按回车移到左侧', 'Server navigator is on the right. Drag it or press Enter to move it left.'],
    ['拖动到左侧或右侧', 'Drag left or right'],
    ['服务器', 'Servers'],
    ['名称、卡型、分区', 'Name, model, partition'],
    ['搜索服务器', 'Search servers'],
    ['筛选服务器', 'Filter servers'],
    ['全部', 'All'],
    ['空闲', 'Available'],
    ['任务', 'Jobs'],
    ['异常', 'Issues'],
    ['收藏', 'Favorites'],
    ['关注任务', 'Watching'],
    ['没有匹配的服务器', 'No matching servers'],
    ['上一台服务器', 'Previous server'],
    ['上一台', 'Previous'],
    ['当前筛选位置', 'Current filtered position'],
    ['下一台服务器', 'Next server'],
    ['下一台', 'Next'],
    ['设置', 'Settings'],
    ['暂停监控', 'Pause monitoring'],
    ['正在初始化', 'Initializing'],
    ['立即刷新', 'Refresh now'],
    ['设置与服务器', 'Settings and servers'],
    ['本地配置', 'Local configuration'],
    ['先用自动发现完成常见设置，需要时再展开登录与高级选项。', 'Start with auto-discovery, then expand sign-in and advanced options only when needed.'],
    ['设置内容显示方式', 'Settings content display'],
    ['关闭设置', 'Close settings'],
    ['首次配置进度', 'First-time setup progress'],
    ['了解用途', 'Overview'],
    ['先知道它会做什么', 'See what the app does'],
    ['发现服务器', 'Discover servers'],
    ['自动查找或打开教程', 'Discover automatically or open the guide'],
    ['检查并完成', 'Review and finish'],
    ['确认连接与登录方式', 'Confirm connection and sign-in'],
    ['约 1 分钟完成', 'About one minute'],
    ['集中查看每台服务器的 GPU 状态', 'See every server and GPU in one place'],
    ['集中查看 GPU 显存、进程和 Slurm 任务。', 'Monitor GPU memory, processes, and Slurm jobs together.'],
    ['可用显存', 'Available VRAM'],
    ['先看容量与卡型', 'Check capacity and GPU model first'],
    ['任务详情', 'Job details'],
    ['再展开进程和 Slurm', 'Expand processes and Slurm when needed'],
    ['本机配置', 'Local-only settings'],
    ['密码保存在系统凭据库', 'Passwords stay in the system credential store'],
    ['显示与刷新', 'Display and refresh'],
    ['界面与提醒', 'Interface and alerts'],
    ['界面、提醒与更新', 'Interface, alerts, and updates'],
    ['语言、刷新、任务提醒和版本检查', 'Language, refresh, task alerts, and update checks'],
    ['语言、刷新、关闭方式和收藏通知', 'Language, refresh, close behavior, and favorite alerts'],
    ['这些选项只影响这台电脑上的监控界面。', 'These options affect only the monitoring interface on this computer.'],
    ['仅本机', 'This computer only'],
    ['配置名称', 'Profile name'],
    ['刷新间隔（秒）', 'Refresh interval (seconds)'],
    ['界面语言', 'Interface language'],
    ['简体中文', 'Simplified Chinese'],
    ['点击关闭按钮时', 'When the close button is clicked'],
    ['收起到通知区域', 'Minimize to the notification area'],
    ['直接退出应用', 'Exit the app'],
    ['收藏 GPU 可用时提醒', 'Notify me when favorite GPUs are available'],
    ['我的任务结束时提醒', 'Notify me when my tasks finish'],
    ['默认提醒当前账号下的 Slurm 任务与 GPU 进程；也可在任务表中单独关注', 'Notify for this account’s Slurm jobs and GPU processes by default; individual tasks can also be watched.'],
    ['其他用户的任务不会自动关注；只提醒你在任务表中逐项选择的任务。', 'Other users’ tasks are never watched automatically; only tasks you select individually will notify you.'],
    ['单独关注完成提醒', 'Watch this task'],
    ['仅关注这个用户的这一项任务', 'Watch only this task from this user'],
    ['取消单独提醒', 'Stop watching this task'],
    ['已关注', 'Watching'],
    ['关注', 'Watch'],
    ['全部移除', 'Remove all'],
    ['通知中心', 'Notification center'],
    ['任务完成、版本更新与 GPU 可用消息', 'Task completion, updates, and GPU availability messages'],
    ['全部已读', 'Mark all read'],
    ['暂无通知', 'No notifications yet'],
    ['打开通知中心', 'Open notification center'],
    ['任务完成', 'Task completed'],
    ['收藏 GPU 可用', 'Favorite GPU available'],
    ['GPU 条件满足', 'GPU criteria matched'],
    ['版本更新', 'Update available'],
    ['应用通知', 'App notification'],
    ['任务已完成', 'Task completed'],
    ['收藏 GPU 已可用', 'Favorite GPUs are available'],
    ['发现新版本', 'Update available'],
    ['已关注任务', 'Watched tasks'],
    ['只在任务结束时提醒', 'Notify only when a task finishes'],
    ['还没有关注任务', 'No watched tasks yet'],
    ['可在任务表中逐项关注。', 'Watch tasks individually from a task table.'],
    ['项', 'items'],
    ['移除', 'Remove'],
    ['收藏服务器已有 GPU 可用。', 'A favorite server now has an available GPU.'],
    ['应用更新', 'App updates'],
    ['发现新版本后会进入通知中心', 'New versions appear in the notification center.'],
    ['安全一键更新', 'Safe one-click update'],
    ['下载并校验', 'Download and verify'],
    ['查看更新', 'View update'],
    ['检查更新', 'Check for updates'],
    ['整卡空闲或达到设定显存时发送系统通知', 'Send a system notification when a GPU is idle or reaches the memory threshold'],
    ['单卡最低空闲显存（GiB，可选）', 'Minimum free VRAM per GPU (GiB, optional)'],
    ['留空：只提醒整卡空闲', 'Leave empty: notify only for idle GPUs'],
    ['诊断与日志', 'Diagnostics and logs'],
    ['连接异常时使用，复制内容会自动脱敏', 'Use when connections fail; copied details are automatically redacted'],
    ['复制脱敏诊断', 'Copy redacted diagnostics'],
    ['打开日志目录', 'Open log folder'],
    ['服务器发现与导入', 'Server discovery and import'],
    ['自动读取本机 SSH 配置；检测不到时再查看教程', 'Read local SSH configuration automatically; open the guide only when needed'],
    ['把你平时登录的 GPU 服务器加进来', 'Add the GPU servers you already use'],
    ['如果终端里已经能运行 ', 'If your terminal can already run '],
    ['如果终端里已经能运行', 'If your terminal can already run'],
    ['，进入这一步就会自动查找。', ', this step will discover it automatically.'],
    ['服务器导入步骤', 'Server import steps'],
    ['本地扫描 SSH 配置，不连接服务器', 'Scan local SSH configuration without connecting'],
    ['检查类型', 'Review type'],
    ['确认每台服务器是 SSH 直连还是 Slurm', 'Confirm direct SSH or Slurm for each server'],
    ['保存并查看', 'Save and view'],
    ['密码可选，只保存在系统凭据库', 'Passwords are optional and stored only in the system credential store'],
    ['服务器设置文件路径', 'Server configuration file'],
    ['servers.toml 或 ~/.ssh/config', 'servers.toml or ~/.ssh/config'],
    ['启动时自动同步此文件', 'Sync this file at startup'],
    ['自动发现并导入', 'Discover and import'],
    ['导入并替换列表', 'Import and replace list'],
    ['只读取本机服务器别名；不执行配置命令，不连接服务器，不读取私钥、密码或 ', 'Reads only local server aliases. It does not run configuration commands, connect to servers, or read private keys, passwords, or '],
    ['只读取本机服务器别名；不执行配置命令，不连接服务器，不读取私钥、密码或', 'Reads only local server aliases. It does not run configuration commands, connect to servers, or read private keys, passwords, or'],
    ['自动检测不到？', 'Nothing discovered?'],
    ['按 Windows 或 macOS 教程找到 SSH 配置，命令可一键复制', 'Follow the Windows or macOS guide to find SSH configuration and copy commands in one click'],
    ['展开教程', 'Open guide'],
    ['先弄清楚要找什么', 'What you are looking for'],
    ['SSH 配置通常是一个名为 ', 'SSH configuration is usually a text file named '],
    ['SSH 配置通常是一个名为', 'SSH configuration is usually a text file named'],
    ['、没有扩展名的文本文件。终端命令中的 ', ' with no extension. In the terminal command '],
    ['、没有扩展名的文本文件。终端命令中的', 'with no extension. In the terminal command'],
    [' 里，', ', '],
    ['里，', ','],
    [' 就是显存雷达要导入的服务器别名。', ' is the server alias VRAM Radar imports.'],
    ['就是显存雷达要导入的服务器别名。', 'is the server alias VRAM Radar imports.'],
    ['Windows 教程', 'Windows guide'],
    ['PowerShell 是 Windows 自带的命令窗口', 'PowerShell is the command window included with Windows'],
    ['查看步骤', 'View steps'],
    ['先打开 PowerShell', 'Open PowerShell first'],
    ['点击右侧按钮即可打开；也可以按 Windows 键，搜索 ', 'Use the button on the right, or press the Windows key and search for '],
    ['点击右侧按钮即可打开；也可以按 Windows 键，搜索', 'Use the button on the right, or press the Windows key and search for'],
    ['。这里只打开窗口，不会自动执行命令。', '. This opens the window only; it does not run commands automatically.'],
    ['一键打开 PowerShell', 'Open PowerShell'],
    ['让 OpenSSH 告诉你它读取了哪个文件', 'Ask OpenSSH which file it reads'],
    ['点击命令右侧的“复制”，粘贴到刚打开的 PowerShell，再按 Enter。输出中的 ', 'Click Copy, paste the command into PowerShell, and press Enter. The path after '],
    ['点击命令右侧的“复制”，粘贴到刚打开的 PowerShell，再按 Enter。输出中的', 'Click Copy, paste the command into PowerShell, and press Enter. The path after'],
    [' 后面就是配置文件路径。命令不连接服务器；若配置含 ', ' is the configuration file. The command does not connect to a server; if the configuration contains '],
    ['后面就是配置文件路径。命令不连接服务器；若配置含', 'is the configuration file. The command does not connect to a server; if the configuration contains'],
    ['，OpenSSH 仍可能运行其中的本地判断命令。', ', OpenSSH may still run its local condition commands.'],
    ['复制', 'Copy'],
    ['复制 Windows 查找 SSH 配置命令', 'Copy the Windows command for finding SSH configuration'],
    ['查看常用目录', 'Check common folders'],
    ['如果上一步没有显示用户配置，检查 ', 'If the previous step did not show a user configuration, check '],
    ['如果上一步没有显示用户配置，检查', 'If the previous step did not show a user configuration, check'],
    [' 或 ', ' or '],
    ['或', 'or'],
    ['复制 Windows 查看 SSH 目录命令', 'Copy the Windows command for listing the SSH folder'],
    ['还没有 config 文件？创建并打开一个', 'No config file yet? Create and open one'],
    ['下面的命令只会确保 ', 'The following command only makes sure the '],
    ['下面的命令只会确保', 'The following command only makes sure the'],
    [' 目录存在，然后用记事本打开配置文件；已有文件不会被清空。', ' folder exists, then opens the configuration in Notepad. Existing files are not cleared.'],
    ['目录存在，然后用记事本打开配置文件；已有文件不会被清空。', 'folder exists, then opens the configuration in Notepad. Existing files are not cleared.'],
    ['复制 Windows 创建 SSH 配置命令', 'Copy the Windows command for creating SSH configuration'],
    ['macOS 教程', 'macOS guide'],
    ['“终端”是 macOS 自带的命令窗口', 'Terminal is the command window included with macOS'],
    ['先打开“终端”', 'Open Terminal first'],
    ['点击右侧按钮即可打开；也可以按 Command + 空格，搜索“终端”。这里只打开窗口，不会自动执行命令。', 'Use the button on the right, or press Command + Space and search for Terminal. This opens the window only; it does not run commands automatically.'],
    ['一键打开终端', 'Open Terminal'],
    ['点击命令右侧的“复制”，粘贴到刚打开的终端，再按 Return。输出中的 ', 'Click Copy, paste the command into Terminal, and press Return. The path after '],
    ['点击命令右侧的“复制”，粘贴到刚打开的终端，再按 Return。输出中的', 'Click Copy, paste the command into Terminal, and press Return. The path after'],
    ['复制 macOS 查找 SSH 配置命令', 'Copy the macOS command for finding SSH configuration'],
    ['通常是 ', 'Usually '],
    ['通常是', 'Usually'],
    ['；也可能是 ', '; it may also be '],
    ['；也可能是', '; it may also be'],
    ['、Colima 或 OrbStack 的配置。', ', Colima, or OrbStack configuration.'],
    ['复制 macOS 查看 SSH 目录命令', 'Copy the macOS command for listing the SSH folder'],
    ['下面的命令会创建标准目录和文件、设置推荐权限，再用文本编辑器打开。', 'The command creates the standard folder and file, applies recommended permissions, and opens a text editor.'],
    ['复制 macOS 创建 SSH 配置命令', 'Copy the macOS command for creating SSH configuration'],
    ['配置文件应该写什么？查看最小示例', 'What belongs in the file? View a minimal example'],
    ['把示例中的地址和用户名替换为自己的信息。', 'Replace the sample address and username with your own.'],
    [' 是以后在终端和显存雷达中看到的别名。', ' is the alias shown later in the terminal and VRAM Radar.'],
    ['是以后在终端和显存雷达中看到的别名。', 'is the alias shown later in the terminal and VRAM Radar.'],
    ['复制 SSH 配置示例', 'Copy the SSH configuration example'],
    ['使用 VS Code / Cursor Remote-SSH 或其他工具？', 'Using VS Code, Cursor Remote-SSH, or another tool?'],
    ['SSH Config 配置块已复制', 'SSH Config host block copied'],
    ['在 VS Code、Cursor、VSCodium 或 Windsurf 的设置中搜索 ', 'In VS Code, Cursor, VSCodium, or Windsurf settings, search for '],
    ['在 VS Code、Cursor、VSCodium 或 Windsurf 的设置中搜索', 'In VS Code, Cursor, VSCodium, or Windsurf settings, search for'],
    ['。复制显示的完整路径，粘贴到上方“服务器设置文件路径”，再点击“导入并替换列表”。', '. Copy the full path, paste it into Server configuration file above, and click Import and replace list.'],
    ['PuTTY Session 不是 OpenSSH 配置；WSL 中的 ', 'A PuTTY Session is not OpenSSH configuration. '],
    ['PuTTY Session 不是 OpenSSH 配置；WSL 中的', 'A PuTTY Session is not OpenSSH configuration.'],
    [' 也属于 Linux 环境。请先把所需别名转换或复制到当前 Windows/macOS 系统能读取的 OpenSSH config。', ' inside WSL belongs to its Linux environment. Convert or copy the aliases into an OpenSSH config readable by the current Windows or macOS system.'],
    ['也属于 Linux 环境。请先把所需别名转换或复制到当前 Windows/macOS 系统能读取的 OpenSSH config。', 'inside WSL belongs to its Linux environment. Convert or copy the aliases into an OpenSSH config readable by the current Windows or macOS system.'],
    ['找到路径以后', 'After finding the path'],
    ['把完整路径粘贴到上方输入框。', 'Paste the full path into the field above.'],
    ['点击“导入并替换列表”。', 'Click Import and replace list.'],
    ['检查服务器类型和登录方式，最后点击“保存并开始验证”。', 'Review server type and sign-in, then click Save and start validation.'],
    ['已添加的服务器', 'Added servers'],
    ['拖动左侧手柄排序；使用键盘时，聚焦手柄后按上下方向键。连接与登录细节仍放在第二层设置中。', 'Drag the left handle to reorder. For keyboard use, focus the handle and press the arrow keys. Connection and sign-in details remain in the second level.'],
    ['拖动排序；也可按上下方向键', 'Drag to reorder; arrow keys also work'],
    ['拖动服务器排序', 'Drag to reorder server'],
    ['清除搜索后可排序', 'Clear the search to reorder'],
    ['仅一台服务器，无需排序', 'Only one server; no reordering needed'],
    ['手动添加', 'Add manually'],
    ['搜索已添加的服务器', 'Search added servers'],
    ['搜索名称、别名、地址或账号', 'Search name, alias, address, or account'],
    ['稍后设置', 'Set up later'],
    ['取消', 'Cancel'],
    ['上一步', 'Back'],
    ['下一步', 'Next'],
    ['保存并开始验证', 'Save and start validation'],
    ['新服务器', 'New server'],
    ['连接目标与监控类型', 'Connection target and monitoring type'],
    ['测试连接', 'Test connection'],
    ['移除', 'Remove'],
    ['显示名称', 'Display name'],
    ['4090 实验服务器', '4090 lab server'],
    ['连接类型', 'Connection type'],
    ['自动识别（推荐）', 'Auto-detect (recommended)'],
    ['自动识别会在保存验证时实际连接；失败后可手动指定。', 'Auto-detection connects during save validation; choose a type manually if it cannot decide.'],
    ['SSH 直连 / nvidia-smi', 'Direct SSH / nvidia-smi'],
    ['OpenSSH 别名（优先）', 'OpenSSH alias (preferred)'],
    ['主机地址', 'Host address'],
    ['OpenSSH 别名与主机地址填写一个即可。自动导入后通常只需确认连接类型。', 'Enter either an OpenSSH alias or a host address. After auto-import, you usually only need to confirm the connection type.'],
    ['OpenSSH 别名与主机地址填写一个即可。自动导入会沿用 SSH Config，并尽量确认私钥路径和连接类型。', 'Enter either an OpenSSH alias or a host address. Auto-import keeps the SSH config and confirms the key path and connection type when possible.'],
    ['查看已完成任务提醒', 'View completed-task alerts'],
    ['提醒', 'Alert'],
    ['关注', 'Watch'],
    ['已关注', 'Watching'],
    ['登录与高级设置', 'Sign-in and advanced settings'],
    ['用户名、端口、密码、私钥和本地标识', 'Username, port, password, private key, and local ID'],
    ['服务器 ID（仅本机）', 'Server ID (local only)'],
    ['用于保存配置和凭据引用，通常不需要修改。', 'Used for local configuration and credential references; it usually does not need to change.'],
    ['端口', 'Port'],
    ['直连主机始终使用；OpenSSH 别名仅在下方勾选后覆盖。', 'Always used for a direct host; for an OpenSSH alias, enable the override below.'],
    ['覆盖 OpenSSH 配置中的端口', 'Override the port in OpenSSH configuration'],
    ['用户名', 'Username'],
    ['私钥路径（可选）', 'Private key path (optional)'],
    ['选择或粘贴私钥路径', 'Select or paste a private key path'],
    ['OpenSSH 配置文件（可选）', 'OpenSSH configuration file (optional)'],
    ['自动导入会填写来源；切换直连或文件移动后可在这里清除或修改。', 'Auto-import fills in the source. Clear or update it here after switching to direct connection or moving the file.'],
    ['登录密码（可选）', 'Login password (optional)'],
    ['留空则保持已有密码', 'Leave blank to keep the saved password'],
    ['未保存密码', 'No saved password'],
    ['默认使用 OpenSSH、ssh-agent 或私钥', 'Uses OpenSSH, ssh-agent, or a private key by default'],
    ['删除已保存的登录密码', 'Delete saved login password'],
    ['显示其他用户的任务与命令摘要', 'Show job and command summaries for other users'],
    ['SSH 直连：显示其他用户的 GPU 进程与经本地遮盖、限长的命令摘要。', 'Direct SSH: show other users\' GPU processes with locally redacted, length-limited command summaries.'],
    ['Slurm：显示其他用户的作业名、状态与时间；调度器视图不读取完整 shell 命令。', 'Slurm: show other users\' job names, states, and times; the scheduler view does not read full shell commands.'],
    ['未配置免密引导时，已保存的密码用于认证；完成 SSH Key 引导后会优先使用私钥，密码只在密钥被拒绝时本地回退。首次连接前，请先在 OpenSSH 中核对并接受正确的主机密钥。', 'Before SSH Key setup, a saved password is used for authentication. After setup, the private key is preferred and the password is only a local fallback if the key is rejected. Before the first connection, verify and accept the correct host key in OpenSSH.'],
    ['一键配置 SSH 免密登录', 'Set up passwordless SSH'],
    ['安全生成或复用密钥，部署后自动验证', 'Safely generate or reuse a key and verify it after deployment'],
    ['复用现有密钥，部署后自动验证', 'Reuse an existing key and verify it after deployment'],
    ['开始', 'Start'],
    [' 是更方便的服务器登录方式。配置完成后，后续连接通常不需要重复输入密码。', ' provides convenient, secure server sign-in. After setup, later connections usually do not require a password.'],
    ['是更方便的服务器登录方式。配置完成后，后续连接通常不需要重复输入密码。', 'provides convenient, secure server sign-in. After setup, later connections usually do not require a password.'],
    ['私钥始终留在本机；只把公钥写入当前账号的 ', 'The private key always stays on this computer. Only the public key is written to the current account\'s '],
    ['私钥始终留在本机；只把公钥写入当前账号的', 'The private key always stays on this computer. Only the public key is written to the current account\'s'],
    ['远端只做非替换式追加；会检查重复项、文件类型、所有者和权限。', 'The remote file is append-only. Duplicates, file type, owner, and permissions are checked.'],
    ['追加后若验证或本地保存失败，不会自动改写 ', 'If verification or local saving fails after appending, the app will not automatically rewrite '],
    ['追加后若验证或本地保存失败，不会自动改写', 'If verification or local saving fails after appending, the app will not automatically rewrite'],
    ['；会保留匹配密钥并提示重试或精确手动移除。', '. The matching key is retained with instructions to retry or remove that exact key manually.'],
    ['SSH Key 来源', 'SSH Key source'],
    ['使用现有密钥', 'Use an existing key'],
    ['推荐；不会修改本地密钥', 'Recommended; local keys are not modified'],
    ['生成专用密钥', 'Generate a dedicated key'],
    ['不覆盖现有密钥，保存在本机应用配置目录', 'Does not overwrite existing keys; stored in the local app configuration folder'],
    ['现有私钥路径', 'Existing private key path'],
    ['对应公钥路径（可选）', 'Matching public key path (optional)'],
    ['私钥带口令时建议选择 .pub，并先加载 ssh-agent。', 'For a passphrase-protected private key, select the .pub file and load ssh-agent first.'],
    ['生成专用密钥时会发生什么？', 'What happens when a dedicated key is generated?'],
    ['系统生成独立的 Ed25519 密钥，不覆盖 ', 'The app generates a separate Ed25519 key without overwriting files in '],
    ['系统生成独立的 Ed25519 密钥，不覆盖', 'The app generates a separate Ed25519 key without overwriting files in'],
    [' 中任何现有文件。为了后台自动连接，专用私钥不设置密钥口令，并依靠当前系统用户的文件权限保护；需要口令保护时请选择现有密钥并使用 ssh-agent。', '. To support background connections, the dedicated private key has no passphrase and is protected by current-user file permissions. To use a passphrase, choose an existing key and ssh-agent.'],
    ['中任何现有文件。为了后台自动连接，专用私钥不设置密钥口令，并依靠当前系统用户的文件权限保护；需要口令保护时请选择现有密钥并使用 ssh-agent。', 'To support background connections, the dedicated private key has no passphrase and is protected by current-user file permissions. To use a passphrase, choose an existing key and ssh-agent.'],
    ['配置并验证', 'Configure and verify'],
    ['请先保存地址和用户名；如当前密钥不能登录，再保存一次服务器密码。', 'Save the address and username first. If the current key cannot sign in, save the server password once.'],
    ['开始设置', 'Start setup'],
    ['登录账号', 'Login account'],
    ['主目录', 'Home folder'],
    ['暂停', 'Pause'],
    ['GPU 实时显存', 'Live GPU memory'],
    ['卡型', 'GPU model'],
    ['已用显存', 'Used VRAM'],
    ['空闲显存', 'Free VRAM'],
    ['利用率', 'Utilization'],
    ['温度', 'Temperature'],
    ['GPU 进程', 'GPU processes'],
    ['我的进程', 'My processes'],
    ['当前没有我的 GPU 进程', 'I have no active GPU processes'],
    ['其他用户', 'Other users'],
    ['当前没有可见的其他用户 GPU 进程', 'No other user GPU processes are visible'],
    ['说明', 'About'],
    ['显示当前直连服务器可见的 GPU 进程；不是调度队列，不包含排队或完成历史。可见命令只显示经过敏感参数遮盖与长度限制的摘要，其他用户摘要还需在服务器设置中开启。', 'Shows GPU processes visible on the current direct server. This is not a scheduler queue and does not include pending or completed history. Visible commands are redacted and length-limited; summaries for other users must also be enabled in server settings.'],
    ['代码工作目录', 'Code workspace'],
    ['自动定位', 'Auto-detected'],
    ['已复用缓存', 'Cached'],
    ['刷新目录', 'Refresh folder'],
    ['固定当前目录', 'Pin current folder'],
    ['展开已加载', 'Expand loaded folders'],
    ['固定为默认目录', 'Pin as default folder'],
    ['当前文件夹为空', 'This folder is empty'],
    ['展开后读取', 'Load when expanded'],
    ['展开时读取文件夹名称、类型、大小和修改时间', 'Load names, types, sizes, and modification times when expanded'],
    ['登录账号和主目录', 'Login account and home folder'],
    ['收藏服务器', 'Favorite server'],
    ['暂停监控这台服务器', 'Pause monitoring for this server'],
    ['GPU 实时显存，可横向滚动', 'Live GPU memory; scroll horizontally'],
    ['显存占用率', 'VRAM usage'],
    ['复制工作目录路径', 'Copy workspace path'],
    ['代码工作目录结构', 'Code workspace structure'],
    ['复制文件夹路径', 'Copy folder path'],
    ['拖动到左侧', 'Drag to the left'],
    ['Slurm GPU 调度状态 · 刚刚更新', 'Slurm GPU scheduler · updated just now'],
    ['GPU 节点容量', 'GPU node capacity'],
    ['GPU 节点容量，可横向滚动', 'GPU node capacity; scroll horizontally'],
    ['节点', 'Nodes'],
    ['分区', 'Partition'],
    ['卡型 / 单卡显存', 'GPU model / VRAM per GPU'],
    ['空闲 GPU', 'Free GPUs'],
    ['调度显存占用', 'Scheduled VRAM allocation'],
    ['活动任务', 'Active jobs'],
    ['节点状态', 'Node state'],
    ['按 Slurm 已分配整卡计算，不代表进程实时显存', 'Calculated from whole GPUs allocated by Slurm; not live process VRAM'],
    ['已分配', 'Allocated'],
    ['即将完成', 'Completing'],
    ['不可用', 'Unavailable'],
    ['排空中', 'Draining'],
    ['正在排空', 'Draining'],
    ['故障', 'Failed'],
    ['部分占用', 'Partially allocated'],
    ['已保留', 'Reserved'],
    ['维护中', 'Maintenance'],
    ['排队', 'Pending'],
    ['运行', 'Running'],
    ['完成', 'Completed'],
    ['我的任务', 'My jobs'],
    ['正在运行与排队', 'Running and pending'],
    ['当前 GPU 任务队列', 'Current GPU job queue'],
    ['用户', 'User'],
    ['任务 ID', 'Job ID'],
    ['任务名称', 'Job name'],
    ['状态', 'State'],
    ['节点或排队原因', 'Node or pending reason'],
    ['运行时长', 'Elapsed'],
    ['提交时间', 'Submitted'],
    ['时间限额', 'Time limit'],
    ['占用 GPU', 'GPUs'],
    ['我', 'Me'],
    ['运行中', 'Running'],
    ['过去 24 小时结果', 'Results from the last 24 hours'],
    ['近 24 小时 GPU 任务结果', 'GPU job results from the last 24 hours'],
    ['结束时间', 'Ended'],
    ['已完成', 'Completed'],
    ['排队中', 'Pending'],
    ['等待 GPU 资源', 'Waiting for GPU resources'],
    ['尚未开始', 'Not started'],
    ['过去 24 小时内当前账号未看到其他用户的 GPU 终态任务', 'No completed GPU jobs from other users were visible to this account in the last 24 hours'],
    ['仅显示 Slurm 对当前登录账号可见的 GPU 作业；集群权限策略可能隐藏其他用户任务。任务名称来自提交者设置的 Slurm JobName；这里不是计算节点内的 PID 进程列表。', 'Shows GPU jobs visible to the current account through Slurm. Cluster policy may hide other users\' jobs. Job names are Slurm JobName values; this is not a PID process list from compute nodes.'],
    ['集群容量', 'Cluster capacity'],
    ['大集群模式', 'Large-cluster mode'],
    ['节点明细', 'Node details'],
    ['按需读取', 'Load on demand'],
    ['搜索节点', 'Search nodes'],
    ['节点名', 'Node name'],
    ['全部卡型', 'All GPU models'],
    ['全部分区', 'All partitions'],
    ['仅空闲', 'Available only'],
    ['仅异常', 'Issues only'],
    ['筛选', 'Filter'],
    ['展开后按页读取节点', 'Expand to load nodes page by page'],
    ['暂无 GPU 任务', 'No GPU jobs'],
    ['当前没有我的排队或运行中 GPU 任务', 'I have no pending or running GPU jobs'],
    ['当前服务器未提供近期任务历史，仍可查看当前任务。', 'This server does not provide recent job history; current jobs remain available.'],
    ['当前账号未看到其他用户的活动 GPU 任务', 'No active GPU jobs from other users are visible to this account'],
    ['正在配置中', 'Configuring'],
    ['正在配置并验证服务器', 'Configuring and validating server'],
    ['正在连接 SSH、检查Slurm 调度器并读取第一份 GPU 数据；完成前不会显示为错误。', 'Connecting through SSH, checking the Slurm scheduler, and reading the first GPU snapshot. This is not shown as an error while setup is in progress.'],
    ['正在连接 SSH、检查GPU 采集器并读取第一份 GPU 数据；完成前不会显示为错误。', 'Connecting through SSH, checking the GPU collector, and reading the first GPU snapshot. This is not shown as an error while setup is in progress.'],
    ['Slurm GPU 调度状态 · 正在建立首次有效快照', 'Slurm GPU scheduler · creating the first valid snapshot'],
    ['GPU 实时显存 · 正在建立首次有效快照', 'Live GPU memory · creating the first valid snapshot'],
    ['需要认证', 'Authentication required'],
    ['重新验证', 'Validate again'],
    ['连接设置', 'Connection settings'],
    ['上次 GPU 进程', 'Last GPU processes'],
    ['这是上次成功采样时可见的 GPU 进程，不能据此判断它们现在仍在运行。', 'These GPU processes were visible in the last successful sample; this does not mean they are still running.'],
    ['复制节点名', 'Copy node name'],
    ['GPU 调度占用率', 'Scheduled GPU allocation'],
    ['GPU 任务列表，可横向滚动', 'GPU job list; scroll horizontally'],
    ['复制任务 ID', 'Copy job ID'],
    ['显存雷达：资源可用', 'VRAM Radar: resources available'],
    ['你设置的 GPU 条件已有匹配结果。', 'Your GPU requirements now have a matching result.'],
    ['未能检查更新', 'Could not check for updates'],
    ['重试', 'Retry'],
    ['安装并重启', 'Install and restart'],
    ['下载并显示', 'Download and show'],
    ['打开 Release', 'Open Release'],
    ['更新包已通过 GitHub 元数据校验，确认后会安全替换并自动重启。', 'The package passed GitHub metadata validation. After confirmation, it will be replaced safely and the app will restart.'],
    ['更新包会先校验 SHA-256，再在 Finder 中显示。', 'The package will be SHA-256 verified before it is shown in Finder.'],
    ['当前版本需要从 GitHub Release 手动安装。', 'Install this version manually from the GitHub Release.'],
    ['GitHub 暂时限制了匿名检查，请稍后重试', 'GitHub temporarily limited anonymous update checks. Try again later.'],
    ['无法验证 GitHub 的 HTTPS 证书', 'Could not verify the GitHub HTTPS certificate.'],
    ['无法解析 GitHub 地址，请检查 DNS 或网络', 'Could not resolve GitHub. Check DNS or network access.'],
    ['连接 GitHub 超时，请稍后重试', 'The GitHub connection timed out. Try again later.'],
    ['应用缺少 macOS 系统证书信任组件', 'The app is missing macOS system trust support.'],
    ['GitHub 返回了无法解析的响应', 'GitHub returned a response that could not be parsed.'],
    ['GitHub Release 元数据不完整或不受信任', 'GitHub Release metadata is incomplete or untrusted.'],
    ['暂时无法连接 GitHub，请稍后重试', 'Could not connect to GitHub. Try again later.'],
  ]);

  const PATTERNS = [
    [/^状态更新于 (.+) · 每 ([\d,.]+) 秒$/, 'Updated $1 · every $2 seconds'],
    [/^发现 VRAM Radar (.+) 的修复构建$/, 'VRAM Radar $1 repair build available'],
    [/^发现 VRAM Radar (.+)$/, 'VRAM Radar $1 available'],
    [/^当前版本 (.+)。更新包已通过 GitHub 元数据校验，确认后会安全替换并自动重启。$/, 'Current version $1. The package passed GitHub metadata validation and will be replaced safely before restart.'],
    [/^当前版本 (.+)。更新包会先校验 SHA-256，再在 Finder 中显示。$/, 'Current version $1. The package will be SHA-256 verified before it is shown in Finder.'],
    [/^当前版本 (.+)。当前版本需要从 GitHub Release 手动安装。$/, 'Current version $1. Install the update manually from the GitHub Release.'],
    [/^约 ([\d,.]+) 秒后自动重试$/, 'Retrying automatically in about $1 seconds'],
    [/^第 ([\d,.]+) 台服务器：(.+)$/, 'Server $1: $2'],
    [/^已解析 ([\d,.]+) 台服务器候选(.+)$/, 'Parsed $1 server candidates$2'],
    [/^总量 ([\d,.]+) GiB$/, '$1 GiB total'],
    [/^([\d,.]+)\/([\d,.]+) 台监控就绪 · ([\d,.]+) 块 GPU$/, '$1/$2 servers ready · $3 GPUs'],
    [/^GPU 实时显存 · 刚刚更新$/, 'Live GPU memory · updated just now'],
    [/^([\d,.]+) 个可见进程$/, '$1 visible processes'],
    [/^([\d,.]+) 个$/, '$1'],
    [/^([\d,.]+) 位$/, '$1 users'],
    [/^([\d,.]+) 项$/, '$1 items'],
    [/^([\d,.]+)–([\d,.]+) \/ ([\d,.]+) 台$/, '$1–$2 / $3 servers'],
    [/^([\d,.]+) 台$/, '$1 servers'],
    [/^([\d,.]+) GPU · ([\d,.]+) GiB 可用$/, '$1 GPU · $2 GiB free'],
    [/^在线显存池，可用 ([\d,.]+) GiB，共 ([\d,.]+) GiB，可用率 ([\d,.]+)%，状态充足$/, 'Online VRAM pool: $1 GiB free of $2 GiB ($3%), healthy'],
    [/^修改时间：(.+)$/, 'Modified: $1'],
    [/^(.+)，监控就绪，([\d,.]+) GPU · ([\d,.]+) GiB 可用$/, '$1, monitoring ready, $2 GPU · $3 GiB free'],
    [/^收藏 (.+)$/, 'Favorite $1'],
    [/^当前为筛选结果第 ([\d,.]+) 台，共 ([\d,.]+) 台$/, 'Filtered server $1 of $2'],
    [/^拖动第 ([\d,.]+) 台服务器排序；按上下方向键微调$/, 'Drag server $1 to reorder; use the arrow keys for precise movement'],
    [/^(.+) 已移动到第 ([\d,.]+) 位$/, '$1 moved to position $2'],
    [/^(.+) · ([\d,.]+) GiB\/卡$/, '$1 · $2 GiB/GPU'],
    [/^([\d,.]+) 张（共 ([\d,.]+) 张）$/, '$1 free of $2 GPUs'],
    [/^已分配 ([\d,.]+) GiB$/, '$1 GiB allocated'],
    [/^调度器未分配 ([\d,.]+) \/ ([\d,.]+) GiB$/, '$1 / $2 GiB unallocated by scheduler'],
    [/^([\d,.]+) 当前 · ([\d,.]+) 近期$/, '$1 current · $2 recent'],
    [/^([\d,.]+) 条$/, '$1 jobs'],
    [/^([\d,.]+)天([\d,.]+)小时$/, '$1d $2h'],
    [/^([\d,.]+)小时([\d,.]+)分钟$/, '$1h $2m'],
    [/^([\d,.]+)小时$/, '$1h'],
    [/^([\d,.]+)分钟$/, '$1m'],
    [/^([\d,.]+) 张$/, '$1 GPUs'],
    [/^([\d,.]+) 个节点 · 先按卡型和分区汇总$/, '$1 nodes · summarized by GPU model and partition'],
    [/^每页最多 ([\d,.]+) 个节点$/, 'Up to $1 nodes per page'],
    [/^GPU 实时显存 · 最后成功：从未成功$/, 'Live GPU memory · no successful sample yet'],
    [/^错误代码：(.+)。当前没有可显示的 GPU 快照。$/, 'Error code: $1. No GPU snapshot is available.'],
    [/^([\d,.]+) 运行$/, '$1 running'],
    [/^(.+)，监控就绪，([\d,.]+) GPU · ([\d,.]+) GiB 可用，([\d,.]+) 运行$/, '$1, monitoring ready, $2 GPU · $3 GiB free, $4 running'],
    [/^(.+)，需要认证，需要认证$/, '$1, authentication required'],
    [/^([\d,.]+) 天$/, '$1 days'],
    [/^([\d,.]+) 小时$/, '$1 hours'],
    [/^([\d,.]+) 分钟$/, '$1 minutes'],
    [/^([\d,.]+) 秒$/, '$1 seconds'],
  ];
  const ATTRIBUTES = ['aria-label', 'title', 'placeholder'];
  const textRecords = new WeakMap();
  const attributeRecords = new WeakMap();
  let language = 'zh-CN';
  let observer = null;

  function translated(source) {
    const value = String(source ?? '');
    if (language !== 'en' || !/[\u3400-\u9fff]/u.test(value)) return value;
    const leading = value.match(/^\s*/u)?.[0] || '';
    const trailing = value.match(/\s*$/u)?.[0] || '';
    const core = value.slice(leading.length, value.length - trailing.length);
    if (ENGLISH.has(core)) return `${leading}${ENGLISH.get(core)}${trailing}`;
    for (const [pattern, replacement] of PATTERNS) {
      if (pattern.test(core)) return `${leading}${core.replace(pattern, replacement)}${trailing}`;
    }
    return value;
  }

  function updateText(node) {
    if (!node?.parentElement || ['SCRIPT', 'STYLE'].includes(node.parentElement.tagName)) return;
    const current = node.nodeValue || '';
    let record = textRecords.get(node);
    if (record && current === record.rendered && record.language === language) return;
    if (!record || current !== record.rendered) record = {source: current, rendered: current, language};
    record.rendered = language === 'en' ? translated(record.source) : record.source;
    record.language = language;
    textRecords.set(node, record);
    if (current !== record.rendered) node.nodeValue = record.rendered;
  }

  function updateAttribute(element, name) {
    if (!element?.hasAttribute?.(name)) return;
    const current = element.getAttribute(name) || '';
    let records = attributeRecords.get(element);
    if (!records) {
      records = new Map();
      attributeRecords.set(element, records);
    }
    let record = records.get(name);
    if (record && current === record.rendered && record.language === language) return;
    if (!record || current !== record.rendered) record = {source: current, rendered: current, language};
    record.rendered = language === 'en' ? translated(record.source) : record.source;
    record.language = language;
    records.set(name, record);
    if (current !== record.rendered) element.setAttribute(name, record.rendered);
  }

  function localizeTree(root) {
    if (!root) return;
    if (root.nodeType === Node.TEXT_NODE) updateText(root);
    if (root.nodeType === Node.ELEMENT_NODE) ATTRIBUTES.forEach(name => updateAttribute(root, name));
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT);
    let node = walker.nextNode();
    while (node) {
      if (node.nodeType === Node.TEXT_NODE) updateText(node);
      else ATTRIBUTES.forEach(name => updateAttribute(node, name));
      node = walker.nextNode();
    }
  }

  function setLanguage(nextLanguage) {
    language = nextLanguage === 'en' ? 'en' : 'zh-CN';
    document.documentElement.lang = language;
    localizeTree(document.documentElement);
    document.dispatchEvent(new CustomEvent('vram-radar-language-changed', {detail: {language}}));
    return language;
  }

  const api = {
    get language() { return language; },
    setLanguage,
    translateText(source, targetLanguage = 'en') {
      const previous = language;
      language = targetLanguage === 'en' ? 'en' : 'zh-CN';
      const result = translated(source);
      language = previous;
      return result;
    },
  };

  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  if (typeof window === 'undefined' || typeof document === 'undefined') return;
  window.VRAMRadarI18n = api;
  document.addEventListener('DOMContentLoaded', () => {
    localizeTree(document.documentElement);
    observer = new MutationObserver(mutations => {
      for (const mutation of mutations) {
        if (mutation.type === 'characterData') updateText(mutation.target);
        else if (mutation.type === 'attributes') updateAttribute(mutation.target, mutation.attributeName);
        else mutation.addedNodes.forEach(localizeTree);
      }
    });
    observer.observe(document.documentElement, {
      subtree: true,
      childList: true,
      characterData: true,
      attributes: true,
      attributeFilter: ATTRIBUTES,
    });
  }, {once: true});
})();
